// src/constants/words.js

export const WORDS = [
  { word: 'ӀУЬЙРЕ', translation: 'Morning' },
  { word: 'ӀАХАР', translation: 'Lamb' },
  { word: 'ӀАБАР', translation: 'Bucket handle / Bale' },
  { word: 'ӀАДАТ', translation: 'Custom / Tradition' },
  { word: 'ӀАЗАП', translation: 'Torment / Suffering' },
  { word: 'ӀАЛАМ', translation: 'Nature / World' },
  { word: 'ӀАМАР', translation: 'Instruction / Command' },
  { word: 'ӀЕХОР', translation: 'Deception / Cheating' },
  { word: 'ӀЕДАЛ', translation: 'Government / Law' },
  { word: 'ӀЕДАШ', translation: 'Habits / Customs' },
  { word: 'ӀЕЖАН', translation: 'Apple (possessive)' },
  { word: 'ӀЕЖАШ', translation: 'Apples' },
  { word: 'ӀОЖАН', translation: 'Deathly / Fatal' },
  { word: 'ӀОМАН', translation: 'Lake (possessive)' },
  { word: 'СУГӀА', translation: 'Slush / Wet snow' },
  { word: 'РОГӀЕ', translation: 'Turn / Queue (in order)' },
  { word: 'ХӀОРШ', translation: 'These' },
  { word: 'ХӀОСТ', translation: 'Target / Mark' },
  { word: 'УГӀАР', translation: 'Howl / Roar' },
  { word: 'АДДИС', translation: 'Addis (as in Addis Ababa)' },
  { word: 'АЛЖИР', translation: 'Algeria' },
  { word: 'АЛТАЙ', translation: 'Altai' },
  { word: 'АММАН', translation: 'Amman' },
  { word: 'АНГЛИ', translation: 'England' },
  { word: 'АРАВИ', translation: 'Arabia' },
  { word: 'АФИНЫ', translation: 'Athens' },
  { word: 'БАКОХ', translation: 'Baku (Chechen name)' },
  { word: 'БАЛКХ', translation: 'Balkh' },
  { word: 'БАРЗА', translation: 'Mound / Barrow' },
  { word: 'БАСХА', translation: 'Easter (Pascha)' },
  { word: 'БИРМА', translation: 'Burma' },
  { word: 'ВЛКСМ', translation: 'Komsomol (Abbreviation)' },
  { word: 'ВЦСПС', translation: 'Trade Unions (Abbreviation)' },
  { word: 'ВИСЛА', translation: 'Vistula (River)' },
  { word: 'ВОЛГА', translation: 'Volga (River)' },
  { word: 'ГАБОН', translation: 'Gabon' },
  { word: 'ГАЛНЕ', translation: 'Grozny (Chechen name: Solzha-Gala)' },
  { word: 'ГОРНО', translation: 'Gorno (Mountainous)' },
  { word: 'ГРЕЦИ', translation: 'Greece' },
  { word: 'ГРУЗИ', translation: 'Georgia' },
  { word: 'ГУДРИ', translation: 'Gudri (Village name)' },
  { word: 'ГӀОБА', translation: 'Kuban (River/Region)' },
  { word: 'ДИШНИ', translation: 'Dishni (Teip/Clan name)' },
  { word: 'ДНЕПР', translation: 'Dnieper (River)' },
  { word: 'ДУБИН', translation: 'Dubin (Surname)' },
  { word: 'ДУНАЙ', translation: 'Danube (River)' },
  { word: 'ЗАКИН', translation: 'Zakin (Name/Place)' },
  { word: 'ИЙДАЛ', translation: 'Volga (Chechen name)' },
  { word: 'ИНДИН', translation: 'India (possessive form)' },
  { word: 'ИРТЫШ', translation: 'Irtysh (River)' },
  { word: 'ИТАЛИ', translation: 'Italy' },
  { word: 'ЙЕМЕН', translation: 'Yemen' },
  { word: 'КАБУЛ', translation: 'Kabul' },
  { word: 'КИТАЙ', translation: 'China' },
  { word: 'КОНГО', translation: 'Congo' },
  { word: 'КОРЕЯ', translation: 'Korea' },
  { word: 'КОСТА', translation: 'Costa' },
  { word: 'КЪИЛБ', translation: 'South (K’ilba)' },
  { word: 'КӀАЙН', translation: 'White' },
  { word: 'ЛАКХА', translation: 'Upper / High' },
  { word: 'ЛАТВИ', translation: 'Latvia' },
  { word: 'ЛИВАН', translation: 'Lebanon' },
  { word: 'ЛИТВА', translation: 'Lithuania' },
  { word: 'МАКАН', translation: 'Place / Location' },
  { word: 'МАРТА', translation: 'Fort / Martan (River)' },
  { word: 'МИНСК', translation: 'Minsk' },
  { word: 'МИСАР', translation: 'Egypt' },
  { word: 'НАЖИН', translation: 'Oak (possessive)' },
  { word: 'НЕПАЛ', translation: 'Nepal' },
  { word: 'НИГЕР', translation: 'Niger' },
  { word: 'ОБАРГ', translation: 'Abrag (Outlaw/Rebel)' },
  { word: 'ПАМИР', translation: 'Pamir' },
  { word: 'ПАРИЖ', translation: 'Paris' },
  { word: 'ПЕКИН', translation: 'Beijing' },
  { word: 'ПРАГА', translation: 'Prague' },
  { word: 'РСДРП', translation: 'RSDLP (Political Party)' },
  { word: 'РОССИ', translation: 'Russia' },
  { word: 'СЕВАН', translation: 'Sevan' },
  { word: 'СЕЛМА', translation: 'Selma' },
  { word: 'СИПСО', translation: 'Sipso (Proper Name)' },
  { word: 'СОФИЯ', translation: 'Sofia' },
  { word: 'СОЬЛЖ', translation: 'Sunzha (River)' },
  { word: 'СУДАН', translation: 'Sudan' },
  { word: 'СУЬЙР', translation: 'Evening' },
  { word: 'ТЕМЗА', translation: 'Thames' },
  { word: 'ТИБЕТ', translation: 'Tibet' },
  { word: 'ТИЙНА', translation: 'Quiet / Pacific' },
  { word: 'ТОКИО', translation: 'Tokyo' },
  { word: 'ТУНИС', translation: 'Tunisia' },
  { word: 'ТУРЦИ', translation: 'Turkey' },
  { word: 'ХАНОЙ', translation: 'Hanoi' },
  { word: 'ХАСУН', translation: 'Khasun (Proper Name)' },
  { word: 'ХЬАЛА', translation: 'Up / Upward' },
  { word: 'ЦОЦИН', translation: 'Tsotsin (Proper Name)' },
  { word: 'ЧӀУЛГ', translation: 'Ring / Circle' },
  { word: 'ШВЕЦИ', translation: 'Sweden' },
  { word: 'ШОЬНА', translation: 'Shona (Village)' },
  { word: 'ЭЛЬБА', translation: 'Elbe (River)' },
  { word: 'ЯКУТИ', translation: 'Yakutia' },
  { word: 'ЯПОНИ', translation: 'Japan' },
  { word: 'АБАДЕ', translation: 'Eternity' },
  { word: 'АБАЗО', translation: 'Abazin (person)' },
  { word: 'АБЗАЦ', translation: 'Paragraph' },
  { word: 'АБОРТ', translation: 'Abortion' },
  { word: 'АВАНС', translation: 'Advance / Deposit' },
  { word: 'АВАРИ', translation: 'Accident / Emergency' },
  { word: 'АВГОЛ', translation: 'Oriole (bird)' },
  { word: 'АВРАЛ', translation: 'All hands on deck' },
  { word: 'АВСАЛ', translation: 'Wormwood' },
  { word: 'АВТОР', translation: 'Author' },
  { word: 'АГЕНТ', translation: 'Agent' },
  { word: 'АГӀОР', translation: 'Side / Direction' },
  { word: 'АГӀАЗ', translation: 'Annoyance / Irritation' },
  { word: 'АДРЕС', translation: 'Address' },
  { word: 'АЗАЛЕ', translation: 'Eternity (without beginning)' },
  { word: 'АЗДАН', translation: 'To thin out / To weaken' },
  { word: 'АЗДАР', translation: 'Weakening / Thinning' },
  { word: 'АЙТАН', translation: 'Aytan (Proper Name)' },
  { word: 'АЙДАН', translation: 'To raise / To lift' },
  { word: 'АЙДАР', translation: 'Raising / Lifting' },
  { word: 'АКАЦИ', translation: 'Acacia' },
  { word: 'АКТИВ', translation: 'Active / Assets' },
  { word: 'АКТЁР', translation: 'Actor' },
  { word: 'АКУЛА', translation: 'Shark' },
  { word: 'АКХАР', translation: 'Wild / Savage' },
  { word: 'АКХШО', translation: 'Aksho (Proper Name/Ethic)' },
  { word: 'АЛАПА', translation: 'Salary / Wages' },
  { word: 'АЛАША', translation: 'Gelding (horse)' },
  { word: 'АЛЛЕЙ', translation: 'Alley / Lane' },
  { word: 'АЛНИГ', translation: 'Greater / More' },
  { word: 'АЛСАМ', translation: 'Abundant / Plentiful' },
  { word: 'АЛХАШ', translation: 'Carding (wool)' },
  { word: 'АМАЛТ', translation: 'Amanat / Hostage / Trust' },
  { word: 'АМБАР', translation: 'Barn / Granary' },
  { word: 'АМПЕР', translation: 'Ampere' },
  { word: 'АНДИЙ', translation: 'Andian (person)' },
  { word: 'АННАШ', translation: 'Planks / Boards' },
  { word: 'АПАРИ', translation: 'Apar (Proper Name)' },
  { word: 'АРАЗА', translation: 'Discontent / Displeasure' },
  { word: 'АРАРА', translation: 'External / From outside' },
  { word: 'АРАХЬ', translation: 'Outside / Outdoors' },
  { word: 'АРВАН', translation: 'Arvan (Proper Name)' },
  { word: 'АРДАМ', translation: 'Order / Array' },
  { word: 'АРДАН', translation: 'To arrange / To order' },
  { word: 'АРДАШ', translation: 'Arranging / Ordering' },
  { word: 'АРКХО', translation: 'Arkho (Proper Name)' },
  { word: 'АРСАШ', translation: 'Arshins (measure)' },
  { word: 'АРХАШ', translation: 'Reins' },
  { word: 'АРХИВ', translation: 'Archive' },
  { word: 'АСТМА', translation: 'Asthma' },
  { word: 'АТАКА', translation: 'Attack' },
  { word: 'АТАРШ', translation: 'Harrows (tool)' },
  { word: 'АТЛАН', translation: 'Atlantic' },
  { word: 'АТЛАС', translation: 'Atlas / Satin' },
  { word: 'АХБӀЕ', translation: 'Half a hundred (50)' },
  { word: 'АХДОШ', translation: 'Half-word' },
  { word: 'АХКАР', translation: 'Digging / Excavation' },
  { word: 'АХМАХ', translation: 'Foolish / Silly' },
  { word: 'АХСОМ', translation: 'Half a ruble (50 kopeks)' },
  { word: 'АХЬАР', translation: 'Flour (corn/maize)' },
  { word: 'АЬГНА', translation: 'Bent / Warped' },
  { word: 'АЬЛЛА', translation: 'Said / Spoken' },
  { word: 'АЬЛХА', translation: 'Whetstone' },
  { word: 'АЬЛЧА', translation: 'If said / Having said' },
  { word: 'АЬРГА', translation: 'Raw / Unripe' },
  { word: 'АЬРДА', translation: 'Wild / Fierce' },
  { word: 'АЬРЗУ', translation: 'Eagle' },
  { word: 'АЬРРУ', translation: 'Left (side)' },
  { word: 'АЬРТА', translation: 'Blunt / Dull' },
  { word: 'АЬРТО', translation: 'Left-handedness' },
  { word: 'АЬРХА', translation: 'Stubborn / Untamed' },
  { word: 'АЬРША', translation: 'Arshin (measure)' },
  { word: 'АЬСТА', translation: 'Adze / Hoe' },
  { word: 'АЬТТА', translation: 'Easy / Convenient' },
  { word: 'АЬТТО', translation: 'Success / Convenience' },
  { word: 'АЬТТУ', translation: 'Right (side)' },
  { word: 'АЬХКА', translation: 'In summer' },
  { word: 'АЬХКЕ', translation: 'Summer' },
  { word: 'АЬХЬА', translation: 'Shameful' },
  { word: 'АЬЧКА', translation: 'Iron (metal)' },
  { word: 'БАБИН', translation: 'Grandmother’s' },
  { word: 'БАГАЖ', translation: 'Baggage' },
  { word: 'БАЖИН', translation: 'Cattle’s' },
  { word: 'БАЗАР', translation: 'Market' },
  { word: 'БАЗИС', translation: 'Basis' },
  { word: 'БАЙКА', translation: 'Flannel' },
  { word: 'БАЙНА', translation: 'Lost / Perished' },
  { word: 'БАЙТА', translation: 'To allow / To let' },
  { word: 'БАКХА', translation: 'To extract / To take out' },
  { word: 'БАКХО', translation: 'Right / Justice' },
  { word: 'БАКЪЕ', translation: 'Truth / Reality' },
  { word: 'БАЛБА', translation: 'To stir / To move' },
  { word: 'БАЛДА', translation: 'Lip' },
  { word: 'БАЛЕТ', translation: 'Ballet' },
  { word: 'БАЛЛА', translation: 'Cherry' },
  { word: 'БАЛЛО', translation: 'To fatigue / To weary' },
  { word: 'БАЛОЗ', translation: 'Wax' },
  { word: 'БАЛХА', translation: 'To work' },
  { word: 'БАЛХО', translation: 'Worker' },
  { word: 'БАМБА', translation: 'Cotton' },
  { word: 'БАНАН', translation: 'Banana' },
  { word: 'БАНДА', translation: 'Band / Gang' },
  { word: 'БАНИН', translation: 'Bath’s / Bathhouse’s' },
  { word: 'БАНИА', translation: 'Jar / Can / Bank' },
  { word: 'БАППА', translation: 'Dandelion' },
  { word: 'БАРАК', translation: 'Barracks' },
  { word: 'БАРАМ', translation: 'Measure / Limit' },
  { word: 'БАРЖО', translation: 'To spread / To distribute' },
  { word: 'БАРИН', translation: 'Baron’s' },
  { word: 'БАРНИ', translation: 'Harnessing / Drafting' },
  { word: 'БАРОЛ', translation: 'Steam' },
  { word: 'БАРТА', translation: 'Agreement / Mouth' },
  { word: 'БАРХӀ', translation: 'Eight' },
  { word: 'БАСАР', translation: 'Paint / Color' },
  { word: 'БАСМА', translation: 'Chintz / Printed cloth' },
  { word: 'БАСНИ', translation: 'Fable' },
  { word: 'БАССО', translation: 'Slope / Declivity' },
  { word: 'БАСТА', translation: 'To untie / To unpack' },
  { word: 'БАТТА', translation: 'In the month / To the mouth' },
  { word: 'БАТӀА', translation: 'To tear / To burst' },
  { word: 'БАТӀО', translation: 'To split / To rip' },
  { word: 'БАХАМ', translation: 'Economy / Property' },
  { word: 'БАХЧО', translation: 'Vegetable garden' },
  { word: 'БАХЬО', translation: 'To bring / To carry' },
  { word: 'БАШХА', translation: 'Special / Distinctive' },
  { word: 'БАӀАН', translation: 'Thistle / Bur' },
  { word: 'БАӀАР', translation: 'Sausage (traditional)' },
  { word: 'БЕАНА', translation: 'Four' },
  { word: 'БЕГАШ', translation: 'Jokes / Humour' },
  { word: 'БЕДАН', translation: 'Quail’s' },
  { word: 'БЕДАР', translation: 'Clothes / Clothing' },
  { word: 'БЕДАШ', translation: 'Ducks' },
  { word: 'БЕДДА', translation: 'Running / Fleeing' },
  { word: 'БЕЖАН', translation: 'Cattle / Cow' },
  { word: 'БЕЗАМ', translation: 'Love / Affection' },
  { word: 'БЕЗАН', translation: 'Heavy / Expensive' },
  { word: 'БЕЙТА', translation: 'To let stay / To leave' },
  { word: 'БЕЙТТ', translation: 'Fourteen' },
  { word: 'БЕКХА', translation: 'To avenge / To retaliate' },
  { word: 'БЕКЪА', translation: 'To divide / To share' },
  { word: 'БЕЛАМ', translation: 'Laughter / Joke' },
  { word: 'БЕЛАН', translation: 'Shovel’s / Spade’s' },
  { word: 'БЕЛАШ', translation: 'Shovels / Spades' },
  { word: 'БЕЛЛА', translation: 'Died / Deceased' },
  { word: 'БЕЛХА', translation: 'To cry / To weep' },
  { word: 'БЕЛХИ', translation: 'Collective work / Mutual aid' },
  { word: 'БЕЛХО', translation: 'Worker' },
  { word: 'БЕПИГ', translation: 'Bread' },
  { word: 'БЕРАМ', translation: 'Brine / Sauce' },
  { word: 'БЕРАН', translation: 'Child’s' },
  { word: 'БЕРАХ', translation: 'Pregnant (animals)' },
  { word: 'БЕРЗА', translation: 'To turn / To transform' },
  { word: 'БЕРЗО', translation: 'To finish / To complete' },
  { word: 'БЕСНИ', translation: 'Cheek' },
  { word: 'БЕСТА', translation: 'To swell / To bloat' },
  { word: 'БЕСТО', translation: 'To inflate / To expand' },
  { word: 'БЕТАН', translation: 'Month’s / Moon’s' },
  { word: 'БЕХКЕ', translation: 'Guilty' },
  { word: 'БЕХХА', translation: 'Long (time/distance)' },
  { word: 'БЕХЬА', translation: 'To carry / To lead' },
  { word: 'БЕЦАН', translation: 'Grass’s / Herbal' },
  { word: 'БЕЦАШ', translation: 'Grasses / Herbs' },
  { word: 'БИЙЛА', translation: 'To begin / To start' },
  { word: 'БИЙНА', translation: 'Spent the night' },
  { word: 'БИЙЦА', translation: 'To speak / To discuss' },
  { word: 'БИЙША', translation: 'To lie down / To sleep' },
  { word: 'БИЙШО', translation: 'To put to sleep' },
  { word: 'БИЛЕТ', translation: 'Ticket' },
  { word: 'БИЛЛА', translation: 'Put / Placed' },
  { word: 'БИССА', translation: 'To remain / To stay' },
  { word: 'БИССО', translation: 'To leave behind' },
  { word: 'БИСТА', translation: 'To edge / To border' },
  { word: 'БИТОК', translation: 'Cutlet / Meatball' },
  { word: 'БИТТА', translation: 'Washed' },
  { word: 'БОВДА', translation: 'To run away / To flee' },
  { word: 'БОВЗА', translation: 'To know / To recognize' },
  { word: 'БОВЛА', translation: 'To finish / To exit' },
  { word: 'БОВРГ', translation: 'Heel' },
  { word: 'БОВХА', translation: 'Hot / Warm' },
  { word: 'БОГӀА', translation: 'To drive in / To plant' },
  { word: 'БОЖАЛ', translation: 'Barn / Cowshed' },
  { word: 'БОЙТА', translation: 'To let perish / To destroy' },
  { word: 'БОЛАМ', translation: 'Movement / Trend' },
  { word: 'БОЛАМ', translation: 'Steel’s' },
  { word: 'БОЛАР', translation: 'Gait / Pace' },
  { word: 'БОЛАТ', translation: 'Steel' },
  { word: 'БОЛЛА', translation: 'To hang / To suspend' },
  { word: 'БОМБА', translation: 'Bomb' },
  { word: 'БОРЕЦ', translation: 'Wrestler' },
  { word: 'БОРЕШ', translation: 'Wrestlers (Cyrillicized)' },
  { word: 'БОССА', translation: 'To descend / To land' },
  { word: 'БОССО', translation: 'To lower / To unload' },
  { word: 'БОТТА', translation: 'To mold / To bake' },
  { word: 'БОХАМ', translation: 'Trouble / Disaster' },
  { word: 'БОХАР', translation: 'Ruin / Destruction' },
  { word: 'БОХКА', translation: 'To put / To place (plural objects)' },
  { word: 'БОХОР', translation: 'Destroying / Breaking' },
  { word: 'БОХЧА', translation: 'Wallet / Purse' },
  { word: 'БОЧКА', translation: 'Barrel / Cask' },
  { word: 'БОШТО', translation: 'Apron' },
  { word: 'БОЬРА', translation: 'Hollow / Ravine' },
  { word: 'БОЬХА', translation: 'Dirty / Filthy' },
  { word: 'БОЬХО', translation: 'To dirty / To soil' },
  { word: 'БРАВО', translation: 'Bravo' },
  { word: 'БУГӀА', translation: 'Bull' },
  { word: 'БУКАР', translation: 'Humpbacked' },
  { word: 'БУКЕТ', translation: 'Bouquet' },
  { word: 'БУКЪА', translation: 'Back (body part)' },
  { word: 'БУЛАР', translation: 'Bison' },
  { word: 'БУЛКА', translation: 'Bun / Roll' },
  { word: 'БУЛКЪ', translation: 'Source / Spring' },
  { word: 'БУМЗИ', translation: 'Mosquito' },
  { word: 'БУРАК', translation: 'Beetroot' },
  { word: 'БУРАМ', translation: 'Ferry' },
  { word: 'БУРСА', translation: 'Strict / Severe' },
  { word: 'БУРУН', translation: 'Drill / Auger' },
  { word: 'БУСАР', translation: 'To slice / To cut' },
  { word: 'БУСТА', translation: 'To measure / To compare' },
  { word: 'БУСТО', translation: 'To puff up / To bloat' },
  { word: 'БУУРГ', translation: 'Food / Eatable' },
  { word: 'БУФЕТ', translation: 'Buffet / Pantry' },
  { word: 'БУХКА', translation: 'To sell' },
  { word: 'БУХӀА', translation: 'Owl' },
  { word: 'БУЬГУ', translation: 'Leading / Taking' },
  { word: 'БУЬЙР', translation: 'Order / Command' },
  { word: 'БУЬЙШ', translation: 'Sleeping / Lying' },
  { word: 'БУЬКА', translation: 'Ball' },
  { word: 'БЫТИЕ', translation: 'Being / Existence' },
  { word: 'БӀАРА', translation: 'Walnut / Eye' },
  { word: 'БӀАХО', translation: 'Warrior / Soldier' },
  { word: 'БӀЕЖУ', translation: 'Yearling calf' },
  { word: 'БӀЕШО', translation: 'Century' },
  { word: 'БӀоБА', translation: 'Pigeon' },
  { word: 'БӀоВВ', translation: 'Tower' },
  { word: 'ВОРХӀ', translation: 'Seven' },
  { word: 'ВАГОН', translation: 'Train car' },
  { word: 'ВАГОР', translation: 'Burning / Lighting' },
  { word: 'ВАЙНА', translation: 'Found / To us' },
  { word: 'ВАЙТА', translation: 'To allow / To let' },
  { word: 'ВАЙША', translation: 'Both of us' },
  { word: 'ВАКХА', translation: 'To live / To stay' },
  { word: 'ВАКХО', translation: 'To settle / To house' },
  { word: 'ВАКЪО', translation: 'To dry' },
  { word: 'ВАЛЛА', translation: 'Died (male)' },
  { word: 'ВАЛЛО', translation: 'To lead / To bring' },
  { word: 'ВАЛТИ', translation: 'Valti (Proper Name)' },
  { word: 'ВАЛХО', translation: 'Worker' },
  { word: 'ВАЛЬС', translation: 'Waltz' },
  { word: 'ВАНДА', translation: 'Vandal' },
  { word: 'ВАННА', translation: 'Bathtub' },
  { word: 'ВАРЕН', translation: 'Cooking / Boiling' },
  { word: 'ВАРЖА', translation: 'To spread out' },
  { word: 'ВАРЖО', translation: 'To scatter' },
  { word: 'ВАРКЪ', translation: 'Varnish' },
  { word: 'ВАССО', translation: 'To lower' },
  { word: 'ВАСТА', translation: 'To untie' },
  { word: 'ВАТТА', translation: 'Washed (male)' },
  { word: 'ВАТӀА', translation: 'To tear' },
  { word: 'ВАТӀО', translation: 'To split' },
  { word: 'ВАХКО', translation: 'To intoxicate' },
  { word: 'ВАХТА', translation: 'Watch / Shift' },
  { word: 'ВАХЧО', translation: 'To warm up' },
  { word: 'ВАХЬА', translation: 'To dare' },
  { word: 'ВАХЬО', translation: 'To take / To carry' },
  { word: 'ВАӀДА', translation: 'Promise / Covenant' },
  { word: 'ВЕАНА', translation: 'Came (male)' },
  { word: 'ВЕДАР', translation: 'Bucket' },
  { word: 'ВЕДДА', translation: 'Ran away (male)' },
  { word: 'ВЕЙТА', translation: 'To let' },
  { word: 'ВЕКАЛ', translation: 'Representative / Envoy' },
  { word: 'ВЕКХА', translation: 'To avenge' },
  { word: 'ВЕКЪА', translation: 'To divide' },
  { word: 'ВЕЛЛА', translation: 'Died (male)' },
  { word: 'ВЕЛХА', translation: 'To cry (male)' },
  { word: 'ВЕЛХО', translation: 'To make cry' },
  { word: 'ВЕНАЗ', translation: 'Venas (Proper Name)' },
  { word: 'ВЕНГР', translation: 'Hungarian' },
  { word: 'ВЕНИГ', translation: 'Broom / Whisk' },
  { word: 'ВЕРАС', translation: 'Guardian / Trustee' },
  { word: 'ВЕРЗА', translation: 'To turn' },
  { word: 'ВЕРЗО', translation: 'To finish' },
  { word: 'ВЕРТА', translation: 'Felt cloak (Burka)' },
  { word: 'ВЕСАН', translation: 'Heavy (male)' },
  { word: 'ВЕСАШ', translation: 'Weights / Balances' },
  { word: 'ВЕСЕТ', translation: 'Will / Testament' },
  { word: 'ВЕСТА', translation: 'To swell' },
  { word: 'ВЕСТО', translation: 'To inflate' },
  { word: 'ВЕТТА', translation: 'To beat / To strike' },
  { word: 'ВЕХЬА', translation: 'To carry' },
  { word: 'ВЕШИН', translation: 'Brother’s' },
  { word: 'ВЗВОД', translation: 'Platoon' },
  { word: 'ВИЙЛА', translation: 'To start' },
  { word: 'ВИЙНА', translation: 'Killed / Spent night' },
  { word: 'ВИЙЦА', translation: 'To discuss' },
  { word: 'ВИЛЛА', translation: 'Put / Placed' },
  { word: 'ВИРАН', translation: 'Donkey’s' },
  { word: 'ВИРАХ', translation: 'From donkey' },
  { word: 'ВИССА', translation: 'To remain' },
  { word: 'ВИССО', translation: 'To leave' },
  { word: 'ВКЛАД', translation: 'Contribution / Deposit' },
  { word: 'ВОВЗА', translation: 'To know' },
  { word: 'ВОВРГ', translation: 'Heel' },
  { word: 'ВОВХА', translation: 'Hot' },
  { word: 'ВОГӀА', translation: 'Driving in' },
  { word: 'ВОЙТА', translation: 'To let' },
  { word: 'ВОНИГ', translation: 'The bad one' },
  { word: 'ВОРДА', translation: 'Cart / Wagon' },
  { word: 'ВОРОТ', translation: 'Collar' },
  { word: 'ВОРТА', translation: 'Neck' },
  { word: 'ВОССА', translation: 'To descend' },
  { word: 'ВОССО', translation: 'To lower' },
  { word: 'ВОТТА', translation: 'Baking' },
  { word: 'ВОХКА', translation: 'To sell' },
  { word: 'ВОХЬА', translation: 'Taking' },
  { word: 'ВОЬДА', translation: 'Going' },
  { word: 'ВОӀАН', translation: 'Son’s' },
  { word: 'ВУЗАН', translation: 'Full / Sated' },
  { word: 'ВУКЪА', translation: 'Back' },
  { word: 'ВУСТА', translation: 'To measure' },
  { word: 'ВУСТО', translation: 'To puff up' },
  { word: 'ВУУРГ', translation: 'Food' },
  { word: 'ВУЬЙШ', translation: 'Others / Rest' },
  { word: 'ВЫШКА', translation: 'Tower' },
  { word: 'ГАЗЕТ', translation: 'Newspaper' },
  { word: 'ГАЙКА', translation: 'Nut (hardware)' },
  { word: 'ГАЙТА', translation: 'To show' },
  { word: 'ГАРАЖ', translation: 'Garage' },
  { word: 'ГАРАН', translation: 'Branch’s' },
  { word: 'ГАРЗА', translation: 'Noodle / Scrap' },
  { word: 'ГЕЛИЙ', translation: 'Helium' },
  { word: 'ГЕМАШ', translation: 'Gems / Shields' },
  { word: 'ГЕНАШ', translation: 'Branches' },
  { word: 'ГЕНИГ', translation: 'The distant one' },
  { word: 'ГЕНИЙ', translation: 'Genius' },
  { word: 'ГЕННА', translation: 'Far away' },
  { word: 'ГЕРГА', translation: 'Near / Close' },
  { word: 'ГЕРГО', translation: 'Round / Circular' },
  { word: 'ГЕРИГ', translation: 'Chunk / Piece' },
  { word: 'ГЕРКА', translation: 'Gherkin / Gerk (Proper Name)' },
  { word: 'ГЕРМА', translation: 'Germ' },
  { word: 'ГЕРОЙ', translation: 'Hero' },
  { word: 'ГИБАН', translation: 'Giban (Proper Name)' },
  { word: 'ГИЖУН', translation: 'Gijun (Proper Name)' },
  { word: 'ГИНСУ', translation: 'Ginseng' },
  { word: 'ГИРДА', translation: 'Measure of grain' },
  { word: 'ГИХАА', translation: 'To cross / To ride' },
  { word: 'ГИЧЧО', translation: 'Nettle' },
  { word: 'ГОБАР', translation: 'Clover' },
  { word: 'ГОВЗА', translation: 'Skilled / Clever' },
  { word: 'ГОВРА', translation: 'Horse' },
  { word: 'ГОМАШ', translation: 'Buffaloes' },
  { word: 'ГОМХА', translation: 'Shallow / Thin' },
  { word: 'ГОМХО', translation: 'Thin person' },
  { word: 'ГОНАН', translation: 'Circle’s' },
  { word: 'ГОНАШ', translation: 'Circles' },
  { word: 'ГОРГА', translation: 'Round' },
  { word: 'ГОТТА', translation: 'Narrow / Tight' },
  { word: 'ГОТТО', translation: 'Narrowness' },
  { word: 'ГОЬЖА', translation: 'Bedspread / Blanket' },
  { word: 'ГОЬЗА', translation: 'Goose' },
  { word: 'ГРАММ', translation: 'Gram' },
  { word: 'ГРАФА', translation: 'Column / Line' },
  { word: 'ГУДОК', translation: 'Beep / Siren' },
  { word: 'ГУЖАМ', translation: 'Hole / Cavity' },
  { word: 'ГУЛАМ', translation: 'Collection / Assembly' },
  { word: 'ГУНАН', translation: 'Hill’s' },
  { word: 'ГУРМА', translation: 'Gourmet' },
  { word: 'ГУЬЛА', translation: 'Dog / Hound' },
  { word: 'ГӀАРА', translation: 'Noise / Fame' },
  { word: 'ГӀОГӀ', translation: 'Goose' },
  { word: 'ГӀУРТ', translation: 'Crowd / Throng' },
  { word: 'ГӀАКХ', translation: 'Crow' },
  { word: 'ГӀАЛА', translation: 'City / Tower' },
  { word: 'ГӀАЛХ', translation: 'Step / Pace' },
  { word: 'ГӀАМА', translation: 'Sand' },
  { word: 'ГӀАНТ', translation: 'Chair' },
  { word: 'ГӀАРТ', translation: 'Post / Pillar' },
  { word: 'ГӀЕЛО', translation: 'Oppression' },
  { word: 'ГӀЕРА', translation: 'Detachment / Troop' },
  { word: 'ГӀИЙН', translation: 'Slender / Weak' },
  { word: 'ГӀИНА', translation: 'Weakened' },
  { word: 'ГӀИРС', translation: 'Tools / Equipment' },
  { word: 'ГӀИРТ', translation: 'Effort / Attempt' },
  { word: 'ГӀОРА', translation: 'Power / Strength' },
  { word: 'ГӀОЗА', translation: 'Merry / Happy' },
  { word: 'ГӀОЛА', translation: 'Better / Preferable' },
  { word: 'ГӀОЛИ', translation: 'Better' },
  { word: 'ГӀОРО', translation: 'To freeze' },
  { word: 'ГӀОТА', translation: 'Flock of sheep' },
  { word: 'ГӀУРА', translation: 'Frost' },
  { word: 'ГӀУГӀ', translation: 'Howl' },
  { word: 'ГӀУДА', translation: 'Penalty / Fine' },
  { word: 'ГӀУЛГ', translation: 'Stone / Pebble' },
  { word: 'ГӀУЛЧ', translation: 'Step / Pace' },
  { word: 'ДӀАМА', translation: 'Handle / Hilt' },
  { word: 'ДӀАРА', translation: 'Distant / Far' },
  { word: 'ДАГАР', translation: 'Counting / Calculation' },
  { word: 'ДАДИН', translation: 'Father’s' },
  { word: 'ДАДОР', translation: 'Running / Fleeing' },
  { word: 'ДАЖАР', translation: 'Grazing' },
  { word: 'ДАЖОР', translation: 'Feeding' },
  { word: 'ДАЗАР', translation: 'Weight / Heaviness' },
  { word: 'ДАЗОР', translation: 'To weight' },
  { word: 'ДАИМА', translation: 'Always' },
  { word: 'ДАЙАР', translation: 'Loss / Destruction' },
  { word: 'ДАЙНА', translation: 'Lost / Perished' },
  { word: 'ДАКХА', translation: 'To suck / To live' },
  { word: 'ДАКЪА', translation: 'Part / Portion / Corpse' },
  { word: 'ДАКЪО', translation: 'To dry' },
  { word: 'ДАЛАР', translation: 'Giving / Dying' },
  { word: 'ДАЛЛО', translation: 'To tire' },
  { word: 'ДАЛХО', translation: 'To complain' },
  { word: 'ДАМКА', translation: 'Checkers (game)' },
  { word: 'ДАРБА', translation: 'Cure / Medicine' },
  { word: 'ДАРЖА', translation: 'Rank / To spread' },
  { word: 'ДАРЖО', translation: 'To spread out' },
  { word: 'ДАРИН', translation: 'Silk’s' },
  { word: 'ДАРТА', translation: 'Bustard (bird)' },
  { word: 'ДАРХО', translation: 'To anger' },
  { word: 'ДАССО', translation: 'To empty' },
  { word: 'ДАТАР', translation: 'Appearance' },
  { word: 'ДАТТА', translation: 'Washing' },
  { word: 'ДАТӀА', translation: 'To tear' },
  { word: 'ДАТӀО', translation: 'To split' },
  { word: 'ДАХЧА', translation: 'To stay' },
  { word: 'ДАХЧО', translation: 'To leave stay' },
  { word: 'ДАХЬО', translation: 'To carry' },
  { word: 'ДАЦОР', translation: 'Shortening' },
  { word: 'ДАШАР', translation: 'Melting' },
  { word: 'ДАШОР', translation: 'To melt' },
  { word: 'ДАӀАР', translation: 'Eating / Corrosion' },
  { word: 'ДЕАНА', translation: 'Came' },
  { word: 'ДЕБАР', translation: 'Multiplication' },
  { word: 'ДЕБЕТ', translation: 'Debit' },
  { word: 'ДЕБОР', translation: 'To multiply' },
  { word: 'ДЕВИЗ', translation: 'Motto' },
  { word: 'ДЕГАН', translation: 'Heart’s' },
  { word: 'ДЕГАР', translation: 'Trembling' },
  { word: 'ДЕГОР', translation: 'To shake' },
  { word: 'ДЕДДА', translation: 'Ran away' },
  { word: 'ДЕЗДЕ', translation: 'Holiday / Ceremony' },
  { word: 'ДЕЙТА', translation: 'To let' },
  { word: 'ДЕКАН', translation: 'Sounding / Ringing' },
  { word: 'ДЕКАР', translation: 'Duty / Obligation' },
  { word: 'ДЕКХА', translation: 'To settle / To pay' },
  { word: 'ДЕКЪА', translation: 'To divide' },
  { word: 'ДЕЛАР', translation: 'Laughter' },
  { word: 'ДЕЛКЪ', translation: 'Noon' },
  { word: 'ДЕЛЛА', translation: 'Died' },
  { word: 'ДЕЛХА', translation: 'To cry' },
  { word: 'ДЕЛХО', translation: 'To make cry' },
  { word: 'ДЕМАН', translation: 'Flour’s' },
  { word: 'ДЕНИГ', translation: 'What happened' },
  { word: 'ДЕННА', translation: 'Daily' },
  { word: 'ДЕНОШ', translation: 'Days' },
  { word: 'ДЕРЗА', translation: 'To turn' },
  { word: 'ДЕСТА', translation: 'To swell' },
  { word: 'ДЕСТО', translation: 'To inflate' },
  { word: 'ДЕФИС', translation: 'Hyphen' },
  { word: 'ДЕХАР', translation: 'Request / Plea' },
  { word: 'ДЕХНА', translation: 'Asked / Requested' },
  { word: 'ДЕХХА', translation: 'Long' },
  { word: 'ДЕХЬЕ', translation: 'Other side' },
  { word: 'ДЕЦИН', translation: 'Aunt’s' },
  { word: 'ДЕЧИГ', translation: 'Wood' },
  { word: 'ДЕШАН', translation: 'Word’s' },
  { word: 'ДЕШАР', translation: 'Reading / Studying' },
  { word: 'ДИВАН', translation: 'Sofa' },
  { word: 'ДИГАР', translation: 'Taking' },
  { word: 'ДИЕТА', translation: 'Diet' },
  { word: 'ДИЙЛА', translation: 'To begin' },
  { word: 'ДИЙЦА', translation: 'To speak' },
  { word: 'ДИЙША', translation: 'To sleep' },
  { word: 'ДИЙШО', translation: 'To put to sleep' },
  { word: 'ДИККА', translation: 'Well / Good' },
  { word: 'ДИЛАР', translation: 'Washing' },
  { word: 'ДИЛЛА', translation: 'Placed' },
  { word: 'ДИЛХА', translation: 'Flesh / Meat' },
  { word: 'ДИНАН', translation: 'Religious / Religion’s' },
  { word: 'ДИРША', translation: 'Hornless (animal)' },
  { word: 'ДИССА', translation: 'To remain / To stay' },
  { word: 'ДИССО', translation: 'To leave behind' },
  { word: 'ДИТТА', translation: 'To wash (plural object)' },
  { word: 'ДОВДА', translation: 'To run away / To flee' },
  { word: 'ДОВЗА', translation: 'To know / To recognize' },
  { word: 'ДОВЛА', translation: 'To finish / To exit' },
  { word: 'ДОВРГ', translation: 'Heel' },
  { word: 'ДОВХА', translation: 'Hot / Warm' },
  { word: 'ДОВХО', translation: 'Heat / Warmth' },
  { word: 'ДОГМА', translation: 'Dogma' },
  { word: 'ДОГӀА', translation: 'Rain / Key' },
  { word: 'ДОЖАЛ', translation: 'Barn / Cowshed' },
  { word: 'ДОЖАР', translation: 'Grammatical case / Fall' },
  { word: 'ДОЙТА', translation: 'To let perish / To let kill' },
  { word: 'ДОКЕР', translation: 'Docker' },
  { word: 'ДОЛАР', translation: 'Dollar' },
  { word: 'ДОЛМА', translation: 'Dolma (stuffed leaves)' },
  { word: 'ДОЛОР', translation: 'Starting / Beginning' },
  { word: 'ДОСКА', translation: 'Board / Blackboard' },
  { word: 'ДОССА', translation: 'To descend / To land' },
  { word: 'ДОССО', translation: 'To lower / To unload' },
  { word: 'ДОТТА', translation: 'To pour / To mold' },
  { word: 'ДОХКА', translation: 'To sell / To put' },
  { word: 'ДОХЬУ', translation: 'Carrying / Bringing' },
  { word: 'ДОЦУШ', translation: 'Without' },
  { word: 'ДОЦЦА', translation: 'Short / Briefly' },
  { word: 'ДОШАН', translation: 'Dictionary’s / Word’s' },
  { word: 'ДОШЛО', translation: 'Rider / Cavalryman' },
  { word: 'ДОЬЛА', translation: 'Saliva / Drool' },
  { word: 'ДОӀАН', translation: 'Prayer’s / Stomach’s' },
  { word: 'ДОӀАХ', translation: 'Bone' },
  { word: 'ДРАМА', translation: 'Drama' },
  { word: 'ДРЕЙФ', translation: 'Drift' },
  { word: 'ДРОБЬ', translation: 'Fraction / Pellets' },
  { word: 'ДУЗАР', translation: 'Satiety / Filling' },
  { word: 'ДУЗОР', translation: 'To fill up' },
  { word: 'ДУКЪА', translation: 'Mountain ridge' },
  { word: 'ДУКЪУ', translation: 'Thick / Dense' },
  { word: 'ДУЛАР', translation: 'Bison' },
  { word: 'ДУСТА', translation: 'To measure / To compare' },
  { word: 'ДУСТО', translation: 'To inflate / To expand' },
  { word: 'ДУУРГ', translation: 'Food' },
  { word: 'ДУХАР', translation: 'Clothing / Dress' },
  { word: 'ДУХӀИ', translation: 'Perfume / Scent' },
  { word: 'ДУЦАР', translation: 'Weaving / Braiding' },
  { word: 'ДУЬЙШ', translation: 'Sowing' },
  { word: 'ДУЬНЕ', translation: 'World / Universe' },
  { word: 'ДУЬРА', translation: 'Salty' },
  { word: 'ДУЬРО', translation: 'To salt / To pickle' },
  { word: 'ДУЬХЬ', translation: 'Face / In front of' },
  { word: 'ДУЭЛЬ', translation: 'Duel' },
  { word: 'ДӀАЭН', translation: 'To mix / To blend' },
  { word: 'ДӀАЭР', translation: 'Mixing / Blending' },
  { word: 'ДӀоВШ', translation: 'Poison' },
  { word: 'ЕАММА', translation: 'Four (emphatic)' },
  { word: 'ЕЗАЕН', translation: 'To love / To weigh (female)' },
  { word: 'ЕЗАРГ', translation: 'Lover / Favorite' },
  { word: 'ЕЙНАН', translation: 'Lightweight (female)' },
  { word: 'ЕЙТТА', translation: 'Fourteen' },
  { word: 'ЕКХОЪ', translation: 'Three' },
  { word: 'ЕЛАХЬ', translation: 'Be / If it is (female)' },
  { word: 'ЕЛАЯР', translation: 'Making laugh (female)' },
  { word: 'ЕЛХОР', translation: 'Making cry (female)' },
  { word: 'ЕРЗОР', translation: 'Finishing / Ending' },
  { word: 'ЕРРИГ', translation: 'Whole / All' },
  { word: 'ЕХАРГ', translation: 'The long one' },
  { word: 'ЖӀАРА', translation: 'Cross' },
  { word: 'ЖӀУГА', translation: 'Swarm / Crowd' },
  { word: 'ЖАГӀА', translation: 'Gravel' },
  { word: 'ЖАЙНА', translation: 'Religious book / Amulet' },
  { word: 'ЖАКЕТ', translation: 'Jacket' },
  { word: 'ЖАНСУ', translation: 'Ginseng' },
  { word: 'ЖАХАР', translation: 'Ash' },
  { word: 'ЖАӀАР', translation: 'Cross' },
  { word: 'ЖИЖИГ', translation: 'Meat' },
  { word: 'ЖИММА', translation: 'A little' },
  { word: 'ЖИМХА', translation: 'Junior / Smallest' },
  { word: 'ЖИРАН', translation: 'Fatty / Greasy' },
  { word: 'ЖИРАФ', translation: 'Giraffe' },
  { word: 'ЖОЛАМ', translation: 'Gourd / Pumpkin' },
  { word: 'ЖОЬЛА', translation: 'Stall / Stable' },
  { word: 'ЖОЬРА', translation: 'Widow' },
  { word: 'ЖУГТИ', translation: 'Jew / Jewish' },
  { word: 'ЖУЛАР', translation: 'Bison' },
  { word: 'ЖУЬРГ', translation: 'Bundle / Wrap' },
  { word: 'ЗӀАРА', translation: 'Cross' },
  { word: 'ЗӀУГА', translation: 'Swarm / Throng' },
  { word: 'ЗАБАР', translation: 'Joke / Fun' },
  { word: 'ЗАБОЙ', translation: 'Slaughter / Mining face' },
  { word: 'ЗАБУР', translation: 'Psalm / Zabur' },
  { word: 'ЗАВОД', translation: 'Factory' },
  { word: 'ЗАГӀА', translation: 'Offering / Ritual gift' },
  { word: 'ЗАЙЛА', translation: 'Lever / Bolt' },
  { word: 'ЗАКАЗ', translation: 'Order' },
  { word: 'ЗАКАТ', translation: 'Zakat (alms) / Sunset' },
  { word: 'ЗАКОН', translation: 'Law' },
  { word: 'ЗАЛОГ', translation: 'Pledge / Deposit' },
  { word: 'ЗАРЯД', translation: 'Charge' },
  { word: 'ЗАХАЛ', translation: 'In-law relative' },
  { word: 'ЗАЧЁТ', translation: 'Test / Credit' },
  { word: 'ЗВЕНО', translation: 'Link / Unit' },
  { word: 'ЗЕВНЕ', translation: 'Resonant / Loud' },
  { word: 'ЗЕЗАГ', translation: 'Flower' },
  { word: 'ЗЕЗАН', translation: 'Harmful' },
  { word: 'ЗЕЙТА', translation: 'Olive' },
  { word: 'ЗЕННА', translation: 'Harmed / Damaged' },
  { word: 'ЗИЙЗА', translation: 'To stir / To move' },
  { word: 'ЗИЯРТ', translation: 'Shrine / Ziyarat' },
  { word: 'ЗОВКХ', translation: 'Pleasure / Bliss' },
  { word: 'ЗОРБА', translation: 'Print / Press' },
  { word: 'ЗУЛАМ', translation: 'Evil / Crime / Harm' },
  { word: 'ЗУРМА', translation: 'Zurna (flute)' },
  { word: 'ИЙДАН', translation: 'To mix / To blend' },
  { word: 'ИЙЗАР', translation: 'Pulling / Stretching' },
  { word: 'ИЙМАН', translation: 'Faith / Iman' },
  { word: 'ИЛЛИН', translation: 'Song’s / Epic’s' },
  { word: 'ИНДУС', translation: 'Hindu' },
  { word: 'ИНЖИЛ', translation: 'Gospel / Injeel' },
  { word: 'ИНЖИР', translation: 'Fig' },
  { word: 'ИРАХЬ', translation: 'Awake / Standing' },
  { word: 'ИРГӀУ', translation: 'Crane (bird)' },
  { word: 'ИРДАН', translation: 'To sharpen' },
  { word: 'ИРДАР', translation: 'Sharpening' },
  { word: 'ИСБӀЕ', translation: 'Ninety' },
  { word: 'ИСЛАМ', translation: 'Islam' },
  { word: 'ИСХАР', translation: 'Woolen cloth' },
  { word: 'ИЧМИК', translation: 'Soft boots (Ichig)' },
  { word: 'ИШКАП', translation: 'Cabinet / Cupboard' },
  { word: 'ИШТТА', translation: 'So / Thus' },
  { word: 'ЙИГАР', translation: 'Taking / Marriage' },
  { word: 'ЙИЙЛА', translation: 'To laugh' },
  { word: 'ЙИЙНА', translation: 'Killed / Spent night' },
  { word: 'ЙИЙЦА', translation: 'To speak about / Discuss' },
  { word: 'ЙИЙША', translation: 'To lie down / To sleep' },
  { word: 'ЙИЙШО', translation: 'To put to sleep' },
  { word: 'ЙИЛЛА', translation: 'Set / Placed' },
  { word: 'ЙИРАН', translation: 'Donkey’s' },
  { word: 'ЙИССА', translation: 'To remain' },
  { word: 'ЙИССО', translation: 'To leave' },
  { word: 'ЙИТАБ', translation: 'Book (archaic)' },
  { word: 'ЙИТТА', translation: 'Washing' },
  { word: 'ЙИШИН', translation: 'Sister’s' },
  { word: 'ЙОВДА', translation: 'To run' },
  { word: 'ЙОВЗА', translation: 'To know' },
  { word: 'ЙОВЛА', translation: 'To exit' },
  { word: 'ЙОВРГ', translation: 'Heel' },
  { word: 'ЙОВХА', translation: 'Hot' },
  { word: 'ЙОВХО', translation: 'Heat' },
  { word: 'ЙОГӀА', translation: 'Planting / Driving in' },
  { word: 'ЙОГӀУ', translation: 'Coming' },
  { word: 'ЙОДАР', translation: 'Running' },
  { word: 'ЙОЙТА', translation: 'To allow' },
  { word: 'ЙОКЪА', translation: 'Drought' },
  { word: 'ЙОЛАН', translation: 'Salary’s' },
  { word: 'ЙОЛАР', translation: 'Starting' },
  { word: 'ЙОЛАХ', translation: 'By wage' },
  { word: 'ЙОЛЛА', translation: 'To send' },
  { word: 'ЙОССА', translation: 'To descend' },
  { word: 'ЙОССО', translation: 'To lower' },
  { word: 'ЙОТТА', translation: 'To pour' },
  { word: 'ЙОХКА', translation: 'To sell' },
  { word: 'ЙОХЪЕ', translation: 'To warm up' },
  { word: 'ЙОьЗА', translation: 'Connected / Link' },
  { word: 'ЙОЬХЬ', translation: 'Sausage / Face / Front' },
  { word: 'ЙОЯЛА', translation: 'To be born / To appear' },
  { word: 'ЙОӀАН', translation: 'Girl’s / Daughter’s' },
  { word: 'КАДАМ', translation: 'Condolence' },
  { word: 'КАДАР', translation: 'Scoop / Dipper' },
  { word: 'КАЗАК', translation: 'Cossack' },
  { word: 'КАЗАХ', translation: 'Kazakh' },
  { word: 'КАКАО', translation: 'Cocoa' },
  { word: 'КАРЕЛ', translation: 'Karelian' },
  { word: 'КАРОР', translation: 'Finding / Discovery' },
  { word: 'КАРТА', translation: 'Map / Card' },
  { word: 'КАРЧА', translation: 'To roll / To wallow' },
  { word: 'КАРЧО', translation: 'To overturn' },
  { word: 'КАСКА', translation: 'Helmet' },
  { word: 'КАССА', translation: 'Cashbox' },
  { word: 'КАСТА', translation: 'Often' },
  { word: 'КАТАР', translation: 'Catarrh' },
  { word: 'КАТЕР', translation: 'Cutter / Boat' },
  { word: 'КАТЕТ', translation: 'Cathetus' },
  { word: 'КАТОД', translation: 'Cathode' },
  { word: 'КАХТО', translation: 'To twist' },
  { word: 'КАЧАЛ', translation: 'Rolling' },
  { word: 'КАЮТА', translation: 'Cabin' },
  { word: 'КАЯЛА', translation: 'To manage' },
  { word: 'КВАРЦ', translation: 'Quartz' },
  { word: 'КЕГАШ', translation: 'Trash / Junk' },
  { word: 'КЕГИЙ', translation: 'Small (plural)' },
  { word: 'КЕДАН', translation: 'Cup’s' },
  { word: 'КЕДАШ', translation: 'Cups' },
  { word: 'КЕЛАП', translation: 'Skein / Yarn' },
  { word: 'КЕНАФ', translation: 'Kenaf' },
  { word: 'КЕНАШ', translation: 'Hulls / Skins' },
  { word: 'КЕНИГ', translation: 'Distant one' },
  { word: 'КЕПАН', translation: 'Form’s / Shape’s' },
  { word: 'КЕПЕК', translation: 'Kopeck' },
  { word: 'КЕПКА', translation: 'Cap' },
  { word: 'КЕРЛА', translation: 'New' },
  { word: 'КЕРЧО', translation: 'Overturning' },
  { word: 'КЕСТА', translation: 'Soon' },
  { word: 'КЕТАР', translation: 'Sheepskin coat' },
  { word: 'КЕХАТ', translation: 'Paper' },
  { word: 'КЕЧАЛ', translation: 'Ornament / Tool' },
  { word: 'КЕЧАМ', translation: 'Preparation' },
  { word: 'КИЙРА', translation: 'Inside / Womb / Stomach' },
  { word: 'КИЙЧА', translation: 'Ready' },
  { word: 'КИОСК', translation: 'Kiosk' },
  { word: 'КИРАН', translation: 'Rent’s' },
  { word: 'КИРША', translation: 'Gray / Ash-colored' },
  { word: 'КИСЕТ', translation: 'Tobacco pouch' },
  { word: 'КИТАН', translation: 'Whale’s' },
  { word: 'КИЧЧА', translation: 'Fully ready' },
  { word: 'КИШМА', translation: 'Raisins' },
  { word: 'КЛАСС', translation: 'Class' },
  { word: 'КЛИКА', translation: 'Clique' },
  { word: 'КНИГА', translation: 'Book' },
  { word: 'КОВРА', translation: 'Caravan' },
  { word: 'КОВСТ', translation: 'Bark' },
  { word: 'КОКОС', translation: 'Coconut' },
  { word: 'КОЛБА', translation: 'Flask' },
  { word: 'КОМАР', translation: 'Mosquito' },
  { word: 'КОМОД', translation: 'Chest of drawers' },
  { word: 'КОМОЛ', translation: 'Camel' },
  { word: 'КОНТР', translation: 'Counter' },
  { word: 'КОНУС', translation: 'Cone' },
  { word: 'КОРТА', translation: 'Head' },
  { word: 'КОТАМ', translation: 'Hen' },
  { word: 'КОТИК', translation: 'Fur seal' },
  { word: 'КОФТА', translation: 'Jacket / Blouse' },
  { word: 'КОХКА', translation: 'To put / To place' },
  { word: 'КОЧАР', translation: 'Necklace' },
  { word: 'КОШАН', translation: 'Grave’s' },
  { word: 'КРОСС', translation: 'Cross' },
  { word: 'КУБИК', translation: 'Cube' },
  { word: 'КУБОК', translation: 'Cup / Trophy' },
  { word: 'КУЗАН', translation: 'Carpet’s' },
  { word: 'КУЛАК', translation: 'Fist / Kulak' },
  { word: 'КУЛЬТ', translation: 'Cult' },
  { word: 'КУПЕЦ', translation: 'Merchant' },
  { word: 'КУРДО', translation: 'Kurd' },
  { word: 'КУХНИ', translation: 'Kitchen' },
  { word: 'КУЧАН', translation: 'Shirt’s' },
  { word: 'КУЧЕР', translation: 'Coachman' },
  { word: 'КУЬРК', translation: 'Oven / Furnace' },
  { word: 'КХАБА', translation: 'To feed / To keep' },
  { word: 'КХАДА', translation: 'To cut' },
  { word: 'КХАЗА', translation: 'To clear' },
  { word: 'КХАЛА', translation: 'To climb' },
  { word: 'КХАЛО', translation: 'To tilt' },
  { word: 'КХАНА', translation: 'Tomorrow' },
  { word: 'КХАНЕ', translation: 'The future' },
  { word: 'КХАНО', translation: 'Later' },
  { word: 'КХАХЬ', translation: 'Take' },
  { word: 'КХЕМА', translation: 'Brain / Logic' },
  { word: 'КХЕРО', translation: 'To frighten' },
  { word: 'КХЕРЧ', translation: 'Hearth' },
  { word: 'КХЕТА', translation: 'To understand / To meet' },
  { word: 'КХЕТО', translation: 'To explain' },
  { word: 'КХИАМ', translation: 'Success' },
  { word: 'КХИОР', translation: 'Development / Education' },
  { word: 'КХОАМ', translation: 'Economy / Saving' },
  { word: 'КХОАН', translation: 'Three’s' },
  { word: 'КХОЗУ', translation: 'Hanging' },
  { word: 'КХОЛА', translation: 'To darken' },
  { word: 'КХОЛО', translation: 'To make dark' },
  { word: 'КХООР', translation: 'Saving' },
  { word: 'КХОЬН', translation: 'Three' },
  { word: 'КХОЬШ', translation: 'Beans' },
  { word: 'КХУЗА', translation: 'Here' },
  { word: 'КХУЬУ', translation: 'Growing' },
  { word: 'КЪАГА', translation: 'To shine' },
  { word: 'КЪАГО', translation: 'To make shine' },
  { word: 'КЪАДА', translation: 'To be exhausted' },
  { word: 'КЪАДО', translation: 'To exhaust' },
  { word: 'КЪАЖА', translation: 'To smile / To grey' },
  { word: 'КЪАНО', translation: 'Elder' },
  { word: 'КЪАРО', translation: 'Decision / Resolution' },
  { word: 'КЪАРШ', translation: 'Hardship' },
  { word: 'КЪАХЬ', translation: 'Bitterness' },
  { word: 'КЪЕЖА', translation: 'To smile / To beam' },
  { word: 'КЪЕНА', translation: 'Old' },
  { word: 'КЪЕРА', translation: 'Destitute' },
  { word: 'КЪЕХО', translation: 'Poor person' },
  { word: 'КЪИЗА', translation: 'Cruel' },
  { word: 'КЪИЛБ', translation: 'South / Qibla' },
  { word: 'КЪОЛА', translation: 'Theft' },
  { word: 'КЪОНА', translation: 'Young' },
  { word: 'КЪОНО', translation: 'Youth' },
  { word: 'КЪОРО', translation: 'Deaf person' },
  { word: 'КЪУЙН', translation: 'Thieves’' },
  { word: 'КЪУРД', translation: 'Swallow / Sip' },
  { word: 'КЪУРР', translation: 'Quail' },
  { word: 'КЪУРТ', translation: 'Swallow' },
  { word: 'КӀАДИ', translation: 'Cloth / Fabric' },
  { word: 'КӀАЖА', translation: 'Heel' },
  { word: 'КӀАЙН', translation: 'White' },
  { word: 'КӀАЛД', translation: 'Cottage cheese' },
  { word: 'КӀАНТ', translation: 'Boy / Son' },
  { word: 'КӀАРА', translation: 'Corner / Side' },
  { word: 'КӀАРХ', translation: 'Crust' },
  { word: 'КӀЕДА', translation: 'Soft' },
  { word: 'КӀЕЗА', translation: 'Puppy' },
  { word: 'КӀЕЛО', translation: 'Trap / Underneath' },
  { word: 'КӀИРА', translation: 'Week' },
  { word: 'КӀоРА', translation: 'Coal' },
  { word: 'КӀоШТ', translation: 'District / Region' },
  { word: 'КӀУРЗ', translation: 'Soot' },
  { word: 'ЛААМЕ', translation: 'Free / Independent' },
  { word: 'ЛАДАМ', translation: 'Importance' },
  { word: 'ЛАДАР', translation: 'Leaking / Melting' },
  { word: 'ЛАЗАР', translation: 'Disease / Pain' },
  { word: 'ЛАЙТА', translation: 'To let' },
  { word: 'ЛАКХЕ', translation: 'Height / Top' },
  { word: 'ЛАКЪА', translation: 'To dry up' },
  { word: 'ЛАКЪО', translation: 'To dry' },
  { word: 'ЛАЛАР', translation: 'Melting' },
  { word: 'ЛАЛЛА', translation: 'Driven' },
  { word: 'ЛАЛОР', translation: 'Smelting' },
  { word: 'ЛАМАЗ', translation: 'Prayer (Namaz)' },
  { word: 'ЛАМИН', translation: 'Stair’s / Ladder’s' },
  { word: 'ЛАМПА', translation: 'Lamp' },
  { word: 'ЛАНГА', translation: 'Long' },
  { word: 'ЛАРГА', translation: 'To cut' },
  { word: 'ЛАРЧА', translation: 'Trace' },
  { word: 'ЛАСАР', translation: 'Sowing' },
  { word: 'ЛАСТА', translation: 'To swing' },
  { word: 'ЛАСТО', translation: 'To wave' },
  { word: 'ЛАТАР', translation: 'Fighting / Battle' },
  { word: 'ЛАТТО', translation: 'To keep / To maintain' },
  { word: 'ЛАТЫШ', translation: 'Latvian' },
  { word: 'ЛАХКА', translation: 'To drive away' },
  { word: 'ЛАХЬА', translation: 'To pick up' },
  { word: 'ЛАХЬО', translation: 'To lower' },
  { word: 'ЛАЦАР', translation: 'Capture' },
  { word: 'ЛЕВСИ', translation: 'Scattered' },
  { word: 'ЛЕГАР', translation: 'Falling / Loss' },
  { word: 'ЛЕГАШ', translation: 'Falling' },
  { word: 'ЛЕДАН', translation: 'Melting' },
  { word: 'ЛЕДАР', translation: 'Weak / Careless' },
  { word: 'ЛЕЖИГ', translation: 'Gizzard' },
  { word: 'ЛЕЙТА', translation: 'To let' },
  { word: 'ЛЕКХА', translation: 'High' },
  { word: 'ЛЕКХО', translation: 'Higher' },
  { word: 'ЛЕКЦИ', translation: 'Lecture' },
  { word: 'ЛЕКЪА', translation: 'To dry up' },
  { word: 'ЛЕЛАР', translation: 'Behavior / Movement' },
  { word: 'ЛЕЛЛА', translation: 'Walked / Been' },
  { word: 'ЛЕЛОР', translation: 'Usage / Driving' },
  { word: 'ЛЕЛХА', translation: 'To jump' },
  { word: 'ЛЕЛХО', translation: 'To blow up' },
  { word: 'ЛЕНАН', translation: 'Lens’s' },
  { word: 'ЛЕНАШ', translation: 'Lenses' },
  { word: 'ЛЕНТА', translation: 'Ribbon / Tape' },
  { word: 'ЛЕСТА', translation: 'To swing' },
  { word: 'ЛЕСТО', translation: 'To wave' },
  { word: 'ЛЕХАР', translation: 'Search' },
  { word: 'ЛЕХКА', translation: 'To drive out' },
  { word: 'ЛЕХЬО', translation: 'To lower' },
  { word: 'ЛЕЦАР', translation: 'Catching' },
  { word: 'ЛЕЧИН', translation: 'Falcon’s' },
  { word: 'ЛИЙЗА', translation: 'To stir' },
  { word: 'ЛИЙЧА', translation: 'To bathe' },
  { word: 'ЛИЙЧО', translation: 'To wash' },
  { word: 'ЛИЛХА', translation: 'Sparse / Flabby' },
  { word: 'ЛИМОН', translation: 'Lemon' },
  { word: 'ЛИСТА', translation: 'To leaf through / Thick' },
  { word: 'ЛОВЗУ', translation: 'Playing' },
  { word: 'ЛОВРГ', translation: 'Heel / Leg bone' },
  { word: 'ЛОВСА', translation: 'To stir / To move' },
  { word: 'ЛОГАН', translation: 'Neck / Throat' },
  { word: 'ЛОЛЛА', translation: 'Slavery / Servitude' },
  { word: 'ЛОРАХ', translation: 'In the path / By the track' },
  { word: 'ЛУУРГ', translation: 'The one who wants' },
  { word: 'ЛУЬРА', translation: 'Strict / Severe' },
  { word: 'ЛУЬСТ', translation: 'Dense / Thickly' },
  { word: 'ЛЫЖАШ', translation: 'Skis' },
  { word: 'МАГАР', translation: 'Health / Ability' },
  { word: 'МАГОР', translation: 'To approve / To permit' },
  { word: 'МАДАР', translation: 'Exposing / Uncovering' },
  { word: 'МАЖАР', translation: 'Musket / Flintlock' },
  { word: 'МАЗАЛ', translation: 'Sweetness / Honey-like' },
  { word: 'МАЗУТ', translation: 'Fuel oil' },
  { word: 'МАЙДА', translation: 'Square / Area' },
  { word: 'МАЙОР', translation: 'Major (rank)' },
  { word: 'МАЙРО', translation: 'Bravely' },
  { word: 'МАЛАР', translation: 'Drink / Beverage' },
  { word: 'МАЛИК', translation: 'Angel' },
  { word: 'МАЛЯР', translation: 'Painter' },
  { word: 'МАМАГ', translation: 'Berry' },
  { word: 'МАРДА', translation: 'Father-in-law' },
  { word: 'МАРКА', translation: 'Stamp' },
  { word: 'МАРЛИ', translation: 'Gauze' },
  { word: 'МАРОШ', translation: 'Noses' },
  { word: 'МАРТА', translation: 'Breakfast / Meal' },
  { word: 'МАРЦА', translation: 'With the husband' },
  { word: 'МАРЧО', translation: 'Shroud' },
  { word: 'МАРША', translation: 'Free / Welcome' },
  { word: 'МАСАЛ', translation: 'Example' },
  { word: 'МАСАР', translation: 'Chamois' },
  { word: 'МАСЕХ', translation: 'Several' },
  { word: 'МАССА', translation: 'All / How many' },
  { word: 'МАССО', translation: 'Every / All' },
  { word: 'МАЦАХ', translation: 'Long ago / Once' },
  { word: 'МАЦЦА', translation: 'Sometime / Whenever' },
  { word: 'МАЧИН', translation: 'Shoe’s' },
  { word: 'МАШАР', translation: 'Peace / Reconciliation' },
  { word: 'МАШИН', translation: 'Car / Machine' },
  { word: 'МАЬРС', translation: 'Free / Liberated' },
  { word: 'МЕГАР', translation: 'To suit / To be okay' },
  { word: 'МЕЗАШ', translation: 'Leeches / Bristles' },
  { word: 'МЕКХА', translation: 'Rust' },
  { word: 'МЕЛЛА', translation: 'Drunk / Somewhat' },
  { word: 'МЕЛОШ', translation: 'Warming' },
  { word: 'МЕЛХО', translation: 'Rather / Instead' },
  { word: 'МЕРАН', translation: 'Nose’s' },
  { word: 'МЕРЗА', translation: 'Sweet' },
  { word: 'МЕРЗО', translation: 'Sweetness' },
  { word: 'МЕСАН', translation: 'Hair’s' },
  { word: 'МЕСАШ', translation: 'Hairs' },
  { word: 'МЕТИГ', translation: 'Place / Spot' },
  { word: 'МЕТИС', translation: 'Metis' },
  { word: 'МЕТОД', translation: 'Method' },
  { word: 'МЕТТА', translation: 'Instead / On the tongue' },
  { word: 'МЕХАН', translation: 'Wind’s / Price’s' },
  { word: 'МЕХАШ', translation: 'Winds / Prices' },
  { word: 'МЕХИЙ', translation: 'Needles' },
  { word: 'МИДАЛ', translation: 'Medal' },
  { word: 'МИЙЛА', translation: 'To drink' },
  { word: 'МИЙЛО', translation: 'To water (animals)' },
  { word: 'МИЛЕХ', translation: 'From which' },
  { word: 'МИЛЛА', translation: 'Whoever' },
  { word: 'МИМАР', translation: 'Architect / Pulpit' },
  { word: 'МИМША', translation: 'Specific / Rare' },
  { word: 'МИНЕХ', translation: 'From the mines' },
  { word: 'МИНУС', translation: 'Minus' },
  { word: 'МИНУТ', translation: 'Minute' },
  { word: 'МИСКА', translation: 'Poor / Miserable' },
  { word: 'МИССИ', translation: 'Mission' },
  { word: 'МИЧЧА', translation: 'Anywhere' },
  { word: 'МОГУШ', translation: 'Healthy / Capable' },
  { word: 'МОЖАН', translation: 'Yellow' },
  { word: 'МОКХА', translation: 'Grey / Brown' },
  { word: 'МОКХО', translation: 'To make grey' },
  { word: 'МОЛЛА', translation: 'Mullah' },
  { word: 'МОЛХА', translation: 'Medicine / Powder' },
  { word: 'МОРЗА', translation: 'Brine / Liquid' },
  { word: 'МОРСА', translation: 'Rough / Coarse' },
  { word: 'МОРЯК', translation: 'Sailor' },
  { word: 'МОТОР', translation: 'Motor' },
  { word: 'МОТТА', translation: 'To think / To seem' },
  { word: 'МОХСА', translation: 'Of the land (dialect)' },
  { word: 'МУЗЕЙ', translation: 'Museum' },
  { word: 'МУҚЪА', translation: 'Free / Loose' },
  { word: 'МУҚЪО', translation: 'To free / To loosen' },
  { word: 'МУНДА', translation: 'Carcass / Stuffed skin' },
  { word: 'МУТАХ', translation: 'From the juice' },
  { word: 'МУТТА', translation: 'Juice / Sap' },
  { word: 'МУХХА', translation: 'Anyhow / Somehow' },
  { word: 'МУЬЖГ', translation: 'Mug / Peasant' },
  { word: 'МУЬЛШ', translation: 'Which ones' },
  { word: 'МУЬРГ', translation: 'Viburnum / Berry' },
  { word: 'МӀАЬУ', translation: 'Meow' },
  { word: 'НАГАН', translation: 'Revolver (Nagant)' },
  { word: 'НАЗМА', translation: 'Religious chant' },
  { word: 'НАКХА', translation: 'Chest / Breast' },
  { word: 'НАЛОГ', translation: 'Tax' },
  { word: 'НАЛХА', translation: 'Butter' },
  { word: 'НАРАН', translation: 'Pomegranate’s' },
  { word: 'НАРЯД', translation: 'Order / Outfit' },
  { word: 'НАСОС', translation: 'Pump' },
  { word: 'НАТРИ', translation: 'Sodium' },
  { word: 'НАЬРС', translation: 'Cucumber' },
  { word: 'НАЬРТ', translation: 'Giant (myth)' },
  { word: 'НЕҚЪА', translation: 'Road / Way' },
  { word: 'НЕҚЪЕ', translation: 'Path / Trip' },
  { word: 'НЕЛАН', translation: 'Trap’s' },
  { word: 'НЕМЕЦ', translation: 'German' },
  { word: 'НЕМКА', translation: 'German woman' },
  { word: 'НЕНАН', translation: 'Mother’s' },
  { word: 'НЕСАН', translation: 'Daughter-in-law’s' },
  { word: 'НЕТТО', translation: 'Net (weight)' },
  { word: 'НЕФТЬ', translation: 'Oil / Petroleum' },
  { word: 'НЕХАН', translation: 'Other people’s' },
  { word: 'НЕХАШ', translation: 'Trash / Garbage' },
  { word: 'НЕХЦА', translation: 'With trash' },
  { word: 'НЕХЧА', translation: 'Cheese' },
  { word: 'НЕЦИН', translation: 'Maternal aunt’s' },
  { word: 'НИГАТ', translation: 'Intention (Niyyat)' },
  { word: 'НИЗАМ', translation: 'Order / Discipline' },
  { word: 'НИЙСА', translation: 'Straight / Correct' },
  { word: 'НИЙСО', translation: 'Equality / Justice' },
  { word: 'НИЛХА', translation: 'Sparse / Thin' },
  { word: 'НИЦҚЪ', translation: 'Force / Power' },
  { word: 'НИШКЕ', translation: 'Specific / Rare' },
  { word: 'НОгӀИ', translation: 'Nogai' },
  { word: 'НОЖАН', translation: 'Oak’s' },
  { word: 'НОМЕР', translation: 'Number' },
  { word: 'НОРАН', translation: 'Ray / Beam' },
  { word: 'НОРАШ', translation: 'Rays / Beams' },
  { word: 'НОРМА', translation: 'Norm' },
  { word: 'НОСТА', translation: 'Shin / Leg' },
  { word: 'НОХЧИ', translation: 'Chechen' },
  { word: 'НОХЧО', translation: 'Chechen person' },
  { word: 'НУЬЙР', translation: 'Saddle' },
  { word: 'ОАЗИС', translation: 'Oasis' },
  { word: 'ОБАРГ', translation: 'Outlaw / Rebel' },
  { word: 'ОБЗОР', translation: 'Overview' },
  { word: 'ОБКОМ', translation: 'Regional committee' },
  { word: 'ОБРАЗ', translation: 'Image / Way' },
  { word: 'ОБРОК', translation: 'Tax / Quitrent' },
  { word: 'ОБЪЁМ', translation: 'Volume' },
  { word: 'ООВВАЙ', translation: 'Oh / Alas' },
  { word: 'ОКЕАН', translation: 'Ocean' },
  { word: 'ОКРУГ', translation: 'District' },
  { word: 'ОКХЛО', translation: 'Rolling pin' },
  { word: 'ОҚЪАМ', translation: 'Block / Chunk' },
  { word: 'ОЛИФА', translation: 'Drying oil' },
  { word: 'ОЛЛАР', translation: 'Hanging' },
  { word: 'ОПЕРА', translation: 'Opera' },
  { word: 'ОПИУМ', translation: 'Opium' },
  { word: 'ОРГАН', translation: 'Organ' },
  { word: 'ОРДЕН', translation: 'Order (medal)' },
  { word: 'ОРДЕР', translation: 'Warrant / Order' },
  { word: 'ОРЗАН', translation: 'Specific / Rare' },
  { word: 'ОРЦХА', translation: 'Proper name' },
  { word: 'ОРШОТ', translation: 'Monday' },
  { word: 'ОСАЛА', translation: 'Cowardly / Mean' },
  { word: 'ОТБОЙ', translation: 'Retreat / Tap' },
  { word: 'ОТБОР', translation: 'Selection' },
  { word: 'ОТДЕЛ', translation: 'Department' },
  { word: 'ОТРЯД', translation: 'Detachment' },
  { word: 'ОТТИН', translation: 'Become / Set' },
  { word: 'ОТЧЁТ', translation: 'Report' },
  { word: 'ОХАНА', translation: 'Plowing / Tillage' },
  { word: 'ОЧАКХ', translation: 'Hearth / Fireplace' },
  { word: 'ОЧЕРК', translation: 'Essay / Sketch' },
  { word: 'ОЧЧАМ', translation: 'Grimace' },
  { word: 'ОЬЗИГ', translation: 'Piece / Scrap' },
  { word: 'ОЬЗНА', translation: 'Polite / Refined' },
  { word: 'ОЬМАР', translation: 'Lifetime / Age' },
  { word: 'ОЬНАН', translation: 'Board’s / Shelf’s' },
  { word: 'ОЬНАШ', translation: 'Boards / Shelves' },
  { word: 'ОЬРСИ', translation: 'Russian' },
  { word: 'ОЬШУШ', translation: 'Needed / Necessary' },
  { word: 'ПАЗАТ', translation: 'Sock' },
  { word: 'ПАЙДА', translation: 'Profit / Benefit' },
  { word: 'ПАКЕТ', translation: 'Packet / Package' },
  { word: 'ПАКЛИ', translation: 'Tow / Oakum' },
  { word: 'ПАПКА', translation: 'Folder' },
  { word: 'ПАРАД', translation: 'Parade' },
  { word: 'ПАРДО', translation: 'Curtain / Screen' },
  { word: 'ПАРТА', translation: 'Desk' },
  { word: 'ПАРТИ', translation: 'Party' },
  { word: 'ПАСТА', translation: 'Paste / Melon' },
  { word: 'ПАТАР', translation: 'Leaf' },
  { word: 'ПАЧКА', translation: 'Pack / Bundle' },
  { word: 'ПЕЗАГ', translation: 'Crust of bread' },
  { word: 'ПЕЛАГ', translation: 'Specific / Rare' },
  { word: 'ПЕНАН', translation: 'Wall’s' },
  { word: 'ПЕНСИ', translation: 'Pension' },
  { word: 'ПЕРОН', translation: 'Platform' },
  { word: 'ПЕТАР', translation: 'Apartment' },
  { word: 'ПЕХАШ', translation: 'Lungs' },
  { word: 'ПЕШАН', translation: 'Oven’s / Stove’s' },
  { word: 'ПЕШИК', translation: 'Small stove' },
  { word: 'ПИЛОТ', translation: 'Pilot' },
  { word: 'ПИЛТА', translation: 'Wick / Fuse' },
  { word: 'ПИРАТ', translation: 'Pirate' },
  { word: 'ПИХТА', translation: 'Fir tree' },
  { word: 'ПЛАТО', translation: 'Plateau' },
  { word: 'ПЛИТА', translation: 'Slab / Stove' },
  { word: 'ПОВАР', translation: 'Cook' },
  { word: 'ПОГОН', translation: 'Shoulder strap' },
  { word: 'ПОЕЗД', translation: 'Train' },
  { word: 'ПОЖАР', translation: 'Fire' },
  { word: 'ПОЛАН', translation: 'Field’s' },
  { word: 'ПОЛЛА', translation: 'Butterfly' },
  { word: 'ПОЛШУ', translation: 'Poland' },
  { word: 'ПОЛЮС', translation: 'Pole' },
  { word: 'ПОЛЯК', translation: 'Pole (person)' },
  { word: 'ПОСОЛ', translation: 'Ambassador' },
  { word: 'ПОТАК', translation: 'Duck' },
  { word: 'ПОХАН', translation: 'Talent / Gift' },
  { word: 'ПОХОД', translation: 'Hike / Campaign' },
  { word: 'ПОЧТА', translation: 'Post / Mail' },
  { word: 'ПОШМЕ', translation: 'Shoe / Slipper' },
  { word: 'ПОЭЗИ', translation: 'Poetry' },
  { word: 'ПОЭМА', translation: 'Poem' },
  { word: 'ПРЕМИ', translation: 'Premium / Prize' },
  { word: 'ПРЕНИ', translation: 'Debate / Discussion' },
  { word: 'ПРЕСС', translation: 'Press' },
  { word: 'ПРОЗА', translation: 'Prose' },
  { word: 'ПУДРА', translation: 'Powder' },
  { word: 'ПУЛЬС', translation: 'Pulse' },
  { word: 'ПУНКТ', translation: 'Point' },
  { word: 'ПУРБА', translation: 'Permission' },
  { word: 'ПУРНИ', translation: 'Bakery' },
  { word: 'ПУРХА', translation: 'Transverse' },
  { word: 'ПУРХЕ', translation: 'Transverse / Width' },
  { word: 'ПУСАР', translation: 'Respect / Esteem' },
  { word: 'ПХИЙН', translation: 'Five’s' },
  { word: 'ПХОРА', translation: 'Pregnant (animal)' },
  { word: 'ПХЬАЖ', translation: 'Calf of leg' },
  { word: 'ПХЬАР', translation: 'Master / Craftsman' },
  { word: 'ПХЬИД', translation: 'Frog' },
  { word: 'ПХЬОР', translation: 'Supper / Dinner' },
  { word: 'ПХЬОШ', translation: 'Forearm / Sleeve' },
  { word: 'ПЬЕСА', translation: 'Play' },
  { word: 'ПӀЕЛГ', translation: 'Finger' },
  { word: 'РАДИЙ', translation: 'Radium' },
  { word: 'РАДИО', translation: 'Radio' },
  { word: 'РАЙОН', translation: 'District' },
  { word: 'РАМИН', translation: 'Frame’s' },
  { word: 'РАСХА', translation: 'Roan (horse)' },
  { word: 'РЕЖИМ', translation: 'Regime' },
  { word: 'РЕЙКА', translation: 'Rail / Slat' },
  { word: 'РЕЛЬС', translation: 'Rail' },
  { word: 'РЕНТА', translation: 'Rent' },
  { word: 'РЕЧӀА', translation: 'Wreath' },
  { word: 'РИНЖА', translation: 'Door' },
  { word: 'РИФМА', translation: 'Rhyme' },
  { word: 'РИЦҚЪ', translation: 'Sustenance / Fate' },
  { word: 'РОМАН', translation: 'Novel' },
  { word: 'РОТНИ', translation: 'Company (military)' },
  { word: 'РУБЕЖ', translation: 'Border' },
  { word: 'РУБИН', translation: 'Ruby' },
  { word: 'РУЗБА', translation: 'Friday prayer' },
  { word: 'РУМЫН', translation: 'Romanian' },
  { word: 'РУЧКА', translation: 'Pen / Handle' },
  { word: 'РЮМКА', translation: 'Wine glass' },
  { word: 'САБИН', translation: 'Soap’s' },
  { word: 'САГАЛ', translation: 'Flea' },
  { word: 'САГАН', translation: 'Deer’s' },
  { word: 'САГАР', translation: 'Sawing / Cutting' },
  { word: 'САДАН', translation: 'To endure' },
  { word: 'САДАР', translation: 'Endurance' },
  { word: 'САҚХО', translation: 'Vigilance' },
  { word: 'САҚХТ', translation: 'Defect / Flaw' },
  { word: 'САЛАЗ', translation: 'Sled' },
  { word: 'САЛАМ', translation: 'Greeting' },
  { word: 'САЛДЕ', translation: 'To the left' },
  { word: 'САЛОР', translation: 'Melting' },
  { word: 'САЛТИ', translation: 'Soldier' },
  { word: 'САЛЮТ', translation: 'Salute / Fireworks' },
  { word: 'САМАР', translation: 'Samarium' },
  { word: 'САМАХ', translation: 'In reality / Awake' },
  { word: 'САНАШ', translation: 'Corners / Angles' },
  { word: 'САННА', translation: 'Like / As' },
  { word: 'САПЁР', translation: 'Sapper' },
  { word: 'САРАП', translation: 'Money-changer' },
  { word: 'САРСА', translation: 'To shake / To drizzle' },
  { word: 'САТИН', translation: 'Satin' },
  { word: 'САТТА', translation: 'To bend' },
  { word: 'САТТО', translation: 'To fold / To bend' },
  { word: 'САХЬТ', translation: 'Hour / Watch' },
  { word: 'САЦАМ', translation: 'Decision / Resolution' },
  { word: 'САЦАР', translation: 'Stop / Cessation' },
  { word: 'САЦОР', translation: 'To stop / To delay' },
  { word: 'САЭЦА', translation: 'To breathe / To inhale' },
  { word: 'СЕАНС', translation: 'Session / Show' },
  { word: 'СЕКАЧ', translation: 'Boar / Cleaver' },
  { word: 'СЕКХА', translation: 'To push / To nudge' },
  { word: 'СЕКЦИ', translation: 'Section' },
  { word: 'СЕМСА', translation: 'Loose / Crumbly' },
  { word: 'СЕНАТ', translation: 'Senate' },
  { word: 'СЕНАШ', translation: 'Porches / Vestibules' },
  { word: 'СЕНИГ', translation: 'The cool one' },
  { word: 'СЕНИН', translation: 'Cool / Shady' },
  { word: 'СЕРИЙ', translation: 'Series' },
  { word: 'СЕРЛО', translation: 'Light' },
  { word: 'СЕРСА', translation: 'To shine / To flicker' },
  { word: 'СЕСАГ', translation: 'Wife / Woman' },
  { word: 'СЕССИ', translation: 'Session' },
  { word: 'СЕТАЛ', translation: 'Steel (archaic)' },
  { word: 'СЕТТА', translation: 'To bend / To warp' },
  { word: 'СЕТТО', translation: 'To curve / To bend' },
  { word: 'СЕХЬА', translation: 'To this side' },
  { word: 'СЕХЬЕ', translation: 'this side' },
  { word: 'СЕЦАР', translation: 'Stopping' },
  { word: 'СЕЦОР', translation: 'Delaying' },
  { word: 'СЕЦЦА', translation: 'Stopped / Determined' },
  { word: 'СИБАТ', translation: 'Appearance / Face' },
  { word: 'СИЗАН', translation: 'Line / Stripe' },
  { word: 'СИЙНА', translation: 'Blue / Green' },
  { word: 'СИЙНО', translation: 'To blue / To dye' },
  { word: 'СИЛОС', translation: 'Silage' },
  { word: 'СИЛУН', translation: 'Silun (Proper Name)' },
  { word: 'СИНОШ', translation: 'Souls' },
  { word: 'СИНУС', translation: 'Sine (Math)' },
  { word: 'СИППА', translation: 'Whistle' },
  { word: 'СИРЛА', translation: 'Bright / Light' },
  { word: 'СИРЛО', translation: 'Brightness' },
  { word: 'СКВЕР', translation: 'Public garden / Square' },
  { word: 'СКЛАД', translation: 'Warehouse / Storehouse' },
  { word: 'СМЕНА', translation: 'Shift / Change' },
  { word: 'СМЕТА', translation: 'Estimate' },
  { word: 'СОБАР', translation: 'Patience' },
  { word: 'СОБЕС', translation: 'Social security office' },
  { word: 'СОВЕТ', translation: 'Council / Advice' },
  { word: 'СОВКХ', translation: 'Excess / Surplus' },
  { word: 'СОВСА', translation: 'To multiply / To increase' },
  { word: 'СОВСО', translation: 'To breed / To increase' },
  { word: 'СОВЦА', translation: 'To stop / To stay' },
  { word: 'СОНТА', translation: 'Arrogant / Foolish' },
  { word: 'СОНТО', translation: 'Arrogance / Folly' },
  { word: 'СОРАМ', translation: 'Silt / Mud' },
  { word: 'СОРСА', translation: 'Coarse / Rough' },
  { word: 'СОЬЛА', translation: 'Slat / Lath' },
  { word: 'СПИРТ', translation: 'Alcohol / Spirit' },
  { word: 'СПОРТ', translation: 'Sport' },
  { word: 'ССУДА', translation: 'Loan' },
  { word: 'СТАЙР', translation: 'Ox / Steer' },
  { word: 'СТАКА', translation: 'Glass / Tumbler' },
  { word: 'СТЕНД', translation: 'Stand / Display' },
  { word: 'СУРИЛ', translation: 'Antimony' },
  { word: 'СУХАР', translation: 'Rusk / Cracker' },
  { word: 'СУЬПА', translation: 'Pious / Devout' },
  { word: 'СХЕМА', translation: 'Scheme / Diagram' },
  { word: 'СЦЕНА', translation: 'Stage / Scene' },
  { word: 'СЪЕЗД', translation: 'Congress / Meeting' },
  { word: 'ТАБАР', translation: 'Comforting' },
  { word: 'ТАДАН', translation: 'To repair / To fix' },
  { word: 'ТАДАР', translation: 'Repairing' },
  { word: 'ТАЙГА', translation: 'Taiga' },
  { word: 'ТАЙНА', translation: 'Liked / Agreed' },
  { word: 'ТАЙПА', translation: 'Type / Clan (Teip)' },
  { word: 'ТАЙТА', translation: 'To please' },
  { word: 'ТАЙША', translation: 'Liked / Fit' },
  { word: 'ТАКСА', translation: 'Fixed price' },
  { word: 'ТАКСИ', translation: 'Taxi' },
  { word: 'ТАКХО', translation: 'To drag' },
  { word: 'ТАЛБА', translation: 'Board / Plaque' },
  { word: 'ТАЛЛА', translation: 'To hunt / To track' },
  { word: 'ТАЛОН', translation: 'Coupon / Ticket' },
  { word: 'ТАЛХА', translation: 'To spoil / To rot' },
  { word: 'ТАЛХО', translation: 'To ruin / To damage' },
  { word: 'ТАМАШ', translation: 'Surprise / Wonder' },
  { word: 'ТАПТА', translation: 'Folder / Registry' },
  { word: 'ТАПЧА', translation: 'Platform / Bench' },
  { word: 'ТАРИФ', translation: 'Tariff' },
  { word: 'ТАРНИ', translation: 'Similar / Equal' },
  { word: 'ТАРСА', translation: 'To neigh / To crackle' },
  { word: 'ТАСАР', translation: 'Throwing / Sowing' },
  { word: 'ТАТОЛ', translation: 'Canal / Stream' },
  { word: 'ТАТТА', translation: 'To push' },
  { word: 'ТАХАН', translation: 'Today' },
  { word: 'ТАХКО', translation: 'To swing / To rock' },
  { word: 'ТАХХЬ', translation: 'Directly / At once' },
  { word: 'ТЕАТР', translation: 'Theater' },
  { word: 'ТЕБАР', translation: 'Creeping / Sneaking' },
  { word: 'ТЕВНА', translation: 'Brood / Clutch' },
  { word: 'ТЕГАР', translation: 'Sewing' },
  { word: 'ТЕДАН', translation: 'To arrange / To fix' },
  { word: 'ТЕЗЕТ', translation: 'Mourning / Wake' },
  { word: 'ТЕЗИС', translation: 'Thesis' },
  { word: 'ТЕКСТ', translation: 'Text' },
  { word: 'ТЕКХО', translation: 'To drag' },
  { word: 'ТЕКЪА', translation: 'To crawl / To pray' },
  { word: 'ТЕЛАТ', translation: 'Calf leather' },
  { word: 'ТЕМАШ', translation: 'Themes / Topics' },
  { word: 'ТЕМБР', translation: 'Timbre' },
  { word: 'ТЕНОР', translation: 'Tenor' },
  { word: 'ТЕОРИ', translation: 'Theory' },
  { word: 'ТЕРГО', translation: 'Observation / Attention' },
  { word: 'ТЕРЗА', translation: 'Scales / Balance' },
  { word: 'ТЕРРА', translation: 'Identical / Uniform' },
  { word: 'ТЕРСА', translation: 'To whinny / To neigh' },
  { word: 'ТЕРХИ', translation: 'Shelf / Ledge' },
  { word: 'ТЕСАН', translation: 'Pious / Devout' },
  { word: 'ТЕСАШ', translation: 'Wicks' },
  { word: 'ТЕХКА', translation: 'To swing / To rock' },
  { word: 'ТЕХКО', translation: 'To rock / To shake' },
  { word: 'ТЕШАМ', translation: 'Trust / Faith' },
  { word: 'ТЕШАН', translation: 'Believing / Faithful' },
  { word: 'ТЕШАР', translation: 'Trusting / Believing' },
  { word: 'ТЕШОР', translation: 'To convince' },
  { word: 'ТЕӀОР', translation: 'Pressing / Squeezing' },
  { word: 'ТИГРИ', translation: 'Tigers' },
  { word: 'ТИДАМ', translation: 'Attention / Notice' },
  { word: 'ТИЙЖА', translation: 'To moan / To mourn' },
  { word: 'ТИЙЖО', translation: 'To make moan' },
  { word: 'ТИЙНА', translation: 'Quiet / Still' },
  { word: 'ТИЙСА', translation: 'To throw / To scatter' },
  { word: 'ТИКМА', translation: 'Small piece / Patch' },
  { word: 'ТИЛАР', translation: 'Error / Deviation' },
  { word: 'ТИЛЛА', translation: 'Placed / Put' },
  { word: 'ТИЛОР', translation: 'Leading astray' },
  { word: 'ТИРАЖ', translation: 'Circulation / Print run' },
  { word: 'ТИТТА', translation: 'Washed (plural)' },
  { word: 'ТИТУЛ', translation: 'Title' },
  { word: 'ТКЪЕС', translation: 'Lightning' },
  { word: 'ТКЪЕХ', translation: 'Twenty (approx)' },
  { word: 'ТКЪОВ', translation: 'Specific / Rare' },
  { word: 'ТОВАР', translation: 'Goods / Merchandise' },
  { word: 'ТОВЖА', translation: 'To lean on / To rest' },
  { word: 'ТОВХА', translation: 'Hearth / Fireplace' },
  { word: 'ТОгӀЕ', translation: 'Valley / Plain' },
  { word: 'ТОДАН', translation: 'To fix / To decorate' },
  { word: 'ТОКХО', translation: 'Abundance / Plenty' },
  { word: 'ТОЛАМ', translation: 'Victory' },
  { word: 'ТОЛАН', translation: 'To win / To excel' },
  { word: 'ТОЛАР', translation: 'Winning' },
  { word: 'ТОЛЛА', translation: 'Broken / Crushed' },
  { word: 'ТОМАН', translation: 'Volume / Tome' },
  { word: 'ТОМАТ', translation: 'Tomato' },
  { word: 'ТОНКА', translation: 'Tobacco' },
  { word: 'ТОННА', translation: 'Ton' },
  { word: 'ТОХАР', translation: 'Strike / Blow' },
  { word: 'ТОХКА', translation: 'To beat / To hit' },
  { word: 'ТОЬЛА', translation: 'Dugout / Cave' },
  { word: 'ТРЕСТ', translation: 'Trust / Cartel' },
  { word: 'ТРИЕР', translation: 'Grader / Sorter' },
  { word: 'ТУКАР', translation: 'Scissors' },
  { word: 'ТУРБА', translation: 'Pipe / Tube' },
  { word: 'ТУРКО', translation: 'Turk' },
  { word: 'ТУРКХ', translation: 'Herald / Crier' },
  { word: 'ТУСАР', translation: 'To peel / To slice' },
  { word: 'ТУФЛИ', translation: 'Shoes' },
  { word: 'ТУШАН', translation: 'Lair / Den' },
  { word: 'ТУЬКА', translation: 'Shop / Store' },
  { word: 'ТУЬМА', translation: 'Ten rubles (Tuman)' },
  { word: 'ТУЬРК', translation: 'Turkic' },
  { word: 'ТУЬТА', translation: 'Skull / Head' },
  { word: 'ТУЬТЕ', translation: 'Skull (locative)' },
  { word: 'ТУЬХА', translation: 'Salt' },
  { word: 'ТХАЙН', translation: 'Our own' },
  { word: 'ТХЬОЗ', translation: 'Chisel' },
  { word: 'ТХЬУМ', translation: 'Marrow / Core' },
  { word: 'ТӀАДО', translation: 'To moisten / To wet' },
  { word: 'ТӀАЙН', translation: 'Bridge’s' },
  { word: 'ТӀАЙШ', translation: 'Bridges' },
  { word: 'ТӀАКӀ', translation: 'Specific / Rare' },
  { word: 'ТӀАЛБ', translation: 'Pledge / Pawn' },
  { word: 'ТӀАПА', translation: 'Flat / Level' },
  { word: 'ТӀАРА', translation: 'Palm of hand / Clap' },
  { word: 'ТӀАУС', translation: 'Peacock' },
  { word: 'ТӀЕЛГ', translation: 'Piece / Rag' },
  { word: 'ТӀЕМА', translation: 'Wing / Feather' },
  { word: 'ТӀЕХЬ', translation: 'Behind / After' },
  { word: 'ТӀУЛГ', translation: 'Stone' },
  { word: 'УГГАР', translation: 'Most / Very' },
  { word: 'УЗБЕК', translation: 'Uzbek' },
  { word: 'УЗУРГ', translation: 'Consumer' },
  { word: 'УЙГУР', translation: 'Uyghur' },
  { word: 'УККАЛ', translation: 'Nape of neck' },
  { word: 'УЛХАН', translation: 'Specific / Rare' },
  { word: 'УЛХОЗ', translation: 'Specific / Rare' },
  { word: 'УММАТ', translation: 'Community (Ummah)' },
  { word: 'УСТАВ', translation: 'Charter / Statute' },
  { word: 'УСТАЗ', translation: 'Master / Teacher (Sufi)' },
  { word: 'УТОПИ', translation: 'Utopia' },
  { word: 'УФФАЙ', translation: 'Ouch / Alas' },
  { word: 'УЬЗАШ', translation: 'Tying / Connecting' },
  { word: 'УЬЙРГ', translation: 'Ball of yarn' },
  { word: 'УЬНАН', translation: 'Board’s / Shelf’s' },
  { word: 'УЬХЬА', translation: 'Specific / Rare' },
  { word: 'ФАСОН', translation: 'Style / Fashion' },
  { word: 'ФАУНА', translation: 'Fauna' },
  { word: 'ФЕРЗЬ', translation: 'Queen (chess)' },
  { word: 'ФЕРМА', translation: 'Farm' },
  { word: 'ФИЗИК', translation: 'Physicist' },
  { word: 'ФИЛЬМ', translation: 'Film' },
  { word: 'ФИНИШ', translation: 'Finish' },
  { word: 'ФИНКА', translation: 'Finnish knife' },
  { word: 'ФИРМА', translation: 'Firm / Company' },
  { word: 'ФЛОРА', translation: 'Flora' },
  { word: 'ФЛЯГА', translation: 'Flask' },
  { word: 'ФОКУС', translation: 'Focus / Trick' },
  { word: 'ФОРМА', translation: 'Form / Uniform' },
  { word: 'ФРАЗА', translation: 'Phrase' },
  { word: 'ФРОНТ', translation: 'Front' },
  { word: 'ХАБАР', translation: 'Talk / News' },
  { word: 'ХАДАМ', translation: 'Decision / Cut' },
  { word: 'ХАДАР', translation: 'Cutting / Break' },
  { word: 'ХАДОР', translation: 'To cut / To stop' },
  { word: 'ХАЗАР', translation: 'Hearing / Sound' },
  { word: 'ХАЗНА', translation: 'Treasure / Treasury' },
  { word: 'ХАКАС', translation: 'Khakas' },
  { word: 'ХАЛАР', translation: 'Specific / Rare' },
  { word: 'ХАЛАТ', translation: 'Robe / Gown' },
  { word: 'ХАЛЛА', translation: 'Hardly / With difficulty' },
  { word: 'ХАННА', translation: 'For the time being' },
  { word: 'ХАРЖА', translation: 'To choose / To elect' },
  { word: 'ХАРИН', translation: 'Specific / Rare' },
  { word: 'ХАРЦЕ', translation: 'False / Untrue' },
  { word: 'ХАСТО', translation: 'To praise / To glorify' },
  { word: 'ХАТАР', translation: 'Danger / Harm' },
  { word: 'ХАТТА', translation: 'To ask' },
  { word: 'ХАХКА', translation: 'To gallop / To drive' },
  { word: 'ХЕБАР', translation: 'Wrinkle' },
  { word: 'ХЕЛАШ', translation: 'Specific / Rare' },
  { word: 'ХЕЛИГ', translation: 'Specific / Rare' },
  { word: 'ХЕНИГ', translation: 'Timed / Dated' },
  { word: 'ХЕРЖА', translation: 'To sift / To select' },
  { word: 'ХЕРСИ', translation: 'Piglet' },
  { word: 'ХЕРЦО', translation: 'To overthrow / To upset' },
  { word: 'ХЕСАН', translation: 'Praising' },
  { word: 'ХЕСТО', translation: 'To praise' },
  { word: 'ХЕТТА', translation: 'Asked / Inquired' },
  { word: 'ХЕХКА', translation: 'Galloped / Driven' },
  { word: 'ХЕЧИН', translation: 'Trousers’' },
  { word: 'ХИЙЛА', translation: 'Many / Often' },
  { word: 'ХИЙРА', translation: 'Strange / Foreign' },
  { word: 'ХИЙЦА', translation: 'To change / To replace' },
  { word: 'ХИЙША', translation: 'Sat down (plural)' },
  { word: 'ХИЙШО', translation: 'To seat (plural)' },
  { word: 'ХИЛАМ', translation: 'Event / Incident' },
  { word: 'ХИЛЛА', translation: 'Was / Happened' },
  { word: 'ХИМИК', translation: 'Chemist' },
  { word: 'ХИНЖА', translation: 'Specific / Rare' },
  { word: 'ХИНИГ', translation: 'Aquatic / Watery' },
  { word: 'ХИНКӀ', translation: 'Specific / Rare' },
  { word: 'ХИНЧО', translation: 'Specific / Rare' },
  { word: 'ХИРАН', translation: 'Specific / Rare' },
  { word: 'ХИРЛО', translation: 'Dilution' },
  { word: 'ХИТТА', translation: 'Fixed / Put' },
  { word: 'ХОВХА', translation: 'Soft / Delicate' },
  { word: 'ХОВША', translation: 'To sit down (plural)' },
  { word: 'ХОВШО', translation: 'To seat (plural)' },
  { word: 'ХОЛИН', translation: 'Specific / Rare' },
  { word: 'ХОРАМ', translation: 'Resentment / Sorrow' },
  { word: 'ХОРДА', translation: 'Chord / Notochord' },
  { word: 'ХОРЕЙ', translation: 'Trochee (Poetry)' },
  { word: 'ХОРЖУ', translation: 'Choosing' },
  { word: 'ХОРХА', translation: 'Specific / Rare' },
  { word: 'ХОРША', translation: 'Malaria / Fever' },
  { word: 'ХОСКА', translation: 'Specific / Rare' },
  { word: 'ХОТТА', translation: 'To set / To put' },
  { word: 'ХОХКУ', translation: 'Galloping' },
  { word: 'ХУДАР', translation: 'Porridge' },
  { word: 'ХУЛСТ', translation: 'Canvas / Linen' },
  { word: 'ХУЛЧИ', translation: 'Specific / Rare' },
  { word: 'ХУНАН', translation: 'Whose' },
  { word: 'ХУРАМ', translation: 'Form / Configuration' },
  { word: 'ХУРМА', translation: 'Date (fruit) / Persimmon' },
  { word: 'ХУТАЛ', translation: 'Pitcher / Jug' },
  { word: 'ХУУРГ', translation: 'The knower' },
  { word: 'ХЬАГА', translation: 'To be thirsty / To envy' },
  { word: 'ХЬАГО', translation: 'To dry up / To wither' },
  { word: 'ХЬАгӀ', translation: 'Envy / Malice' },
  { word: 'ХЬАДА', translation: 'To run / To rush' },
  { word: 'ХЬАЖА', translation: 'To look / To check' },
  { word: 'ХЬАЖО', translation: 'To direct / To point' },
  { word: 'ХЬАЙН', translation: 'Your own' },
  { word: 'ХЬАЙЦ', translation: 'Medlar (fruit)' },
  { word: 'ХЬАҚЪ', translation: 'Right / Due' },
  { word: 'ХЬАЛА', translation: 'Upward' },
  { word: 'ХЬАМА', translation: 'Thing / Something' },
  { word: 'ХЬАМЦ', translation: 'Medlar' },
  { word: 'ХЬАРА', translation: 'Mill' },
  { word: 'ХЬАРД', translation: 'Specific / Rare' },
  { word: 'ХЬАСА', translation: 'Vein / Tendon' },
  { word: 'ХЬАСT', translation: 'Spring / Source' },
  { word: 'ХЬАХО', translation: 'To mention / To rub' },
  { word: 'ХЬАША', translation: 'Guest' },
  { word: 'ХЬАШТ', translation: 'Need / Necessity' },
  { word: 'ХЬЕГА', translation: 'To long for / To suffer' },
  { word: 'ХЬЕГО', translation: 'To make suffer' },
  { word: 'ХЬЕЖА', translation: 'To look / To wait' },
  { word: 'ХЬЕЖО', translation: 'To point / To direct' },
  { word: 'ХЬЕНА', translation: 'Fat / Fertile' },
  { word: 'ХЬЕХО', translation: 'To teach / To mention' },
  { word: 'ХЬЕША', translation: 'Guests (plural) / To trample' },
  { word: 'ХЬОВХ', translation: 'Specific / Rare' },
  { word: 'ХЬОЖА', translation: 'Smell / Scent' },
  { word: 'ХЬОЗА', translation: 'Bird / Sparrow' },
  { word: 'ХЬОМЕ', translation: 'Dear / Beloved' },
  { word: 'ХЬУНА', translation: 'To you / For the forest' },
  { word: 'ХӀЕТА', translation: 'Then / So' },
  { word: 'ХӀИРИ', translation: 'Ossetian' },
  { word: 'ХӀОАН', translation: 'Egg’s' },
  { word: 'ХӀОНЦ', translation: 'Trophy / Booty' },
  { word: 'ХӀОРД', translation: 'Sea' },
  { word: 'ХӀУМА', translation: 'Thing' },
  { word: 'ХӀУЬШ', translation: 'Specific / Rare' },
  { word: 'ЦАГУШ', translation: 'Invisible' },
  { word: 'ЦАМЗА', translation: 'Needle / Stinger' },
  { word: 'ЦАНИН', translation: 'Meadow’s' },
  { word: 'ЦАСТА', translation: 'Copper' },
  { word: 'ЦАТАМ', translation: 'Discontent' },
  { word: 'ЦЕНТР', translation: 'Center' },
  { word: 'ЦЕРАН', translation: 'Their' },
  { word: 'ЦЕСТА', translation: 'To cut / To chip' },
  { word: 'ЦЕЦАН', translation: 'Surprised' },
  { word: 'ЦЕЦИЙ', translation: 'Specific / Rare' },
  { word: 'ЦИФРА', translation: 'Digit / Number' },
  { word: 'ЦИЦАН', translation: 'Specific / Rare' },
  { word: 'ЦИЦИГ', translation: 'Cat' },
  { word: 'ЦУЬРГ', translation: 'Scrap / Piece' },
  { word: 'ЦХЬАЪ', translation: 'One' },
  { word: 'ЦӀАЗА', translation: 'Specific / Rare' },
  { word: 'ЦӀАКА', translation: 'Specific / Rare' },
  { word: 'ЦӀАНО', translation: 'Cleanliness / Purity' },
  { word: 'ЦӀАРЗ', translation: 'Specific / Rare' },
  { word: 'ЦӀАХЬ', translation: 'At home' },
  { word: 'ЦӀЕНА', translation: 'Clean / Pure' },
  { word: 'ЦӀЕРА', translation: 'Fire’s / Name’s' },
  { word: 'ЦӀЕРШ', translation: 'Names' },
  { word: 'ЦӀЕХО', translation: 'Reddish' },
  { word: 'ЦӀИЙН', translation: 'Blood’s / House’s' },
  { word: 'ЦӀИНА', translation: 'Purity' },
  { word: 'ЦӀоГА', translation: 'Tail' },
  { word: 'ЦӀоКА', translation: 'Skin / Hide' },
  { word: 'ЦӀоҚЪ', translation: 'Panther / Leopard' },
  { word: 'ЦӀУЛА', translation: 'Specific / Rare' },
  { word: 'ЦӀУРА', translation: 'Red / Fiery' },
  { word: 'ЧАБОЛ', translation: 'Canter / Trot' },
  { word: 'ЧАЛБА', translation: 'Specific / Rare' },
  { word: 'ЧАМДА', translation: 'Suitcase' },
  { word: 'ЧАПХА', translation: 'Raiding / Plundering' },
  { word: 'ЧАРДО', translation: 'Specific / Rare' },
  { word: 'ЧАРIН', translation: 'Specific / Rare' },
  { word: 'ЧАХЧА', translation: 'To sneeze / To splash' },
  { word: 'ЧАХЧО', translation: 'To splash / To drench' },
  { word: 'ЧЕКАН', translation: 'Minting / Stamping' },
  { word: 'ЧЕМАШ', translation: 'Suitcases' },
  { word: 'ЧЕНАН', translation: 'Specific / Rare' },
  { word: 'ЧЕНАШ', translation: 'Specific / Rare' },
  { word: 'ЧЕНИГ', translation: 'The dusty one' },
  { word: 'ЧЕРАШ', translation: 'Specific / Rare' },
  { word: 'ЧЕРМА', translation: 'Barrel / Cask' },
  { word: 'ЧЕРОН', translation: 'Specific / Rare' },
  { word: 'ЧЕТАР', translation: 'Tent / Umbrella' },
  { word: 'ЧЕХКА', translation: 'Fast / Quick' },
  { word: 'ЧЕХКО', translation: 'Velocity / Speed' },
  { word: 'ЧЕШКА', translation: 'Czech (woman)' },
  { word: 'ЧИДАМ', translation: 'Endurance / Patience' },
  { word: 'ЧИРКХ', translation: 'Torch / Lamp' },
  { word: 'ЧИШАН', translation: 'Urinary' },
  { word: 'ЧКЪОП', translation: 'Slap / Crack' },
  { word: 'ЧКЪОР', translation: 'Bark / Skin / Layer' },
  { word: 'ЧОВКА', translation: 'Jackdaw (bird)' },
  { word: 'ЧОВХО', translation: 'To scold / To reproach' },
  { word: 'ЧОЛХЕ', translation: 'Complex / Complicated' },
  { word: 'ЧОРДА', translation: 'Coarse / Rough' },
  { word: 'ЧОРПА', translation: 'Soup / Broth' },
  { word: 'ЧУАТА', translation: 'To drive in / To push in' },
  { word: 'ЧУВАШ', translation: 'Chuvash (person)' },
  { word: 'ЧУДАР', translation: 'Porridge / Gruel' },
  { word: 'ЧУДОН', translation: 'Cast iron' },
  { word: 'ЧУЖАН', translation: 'Foreigner / Alien' },
  { word: 'ЧУИДА', translation: 'To pour in' },
  { word: 'ЧУИДО', translation: 'To let pour in' },
  { word: 'ЧУОЗА', translation: 'To pull in' },
  { word: 'ЧУТТА', translation: 'Poured in' },
  { word: 'ЧУХАА', translation: 'To sit inside' },
  { word: 'ЧУХАО', translation: 'To seat inside' },
  { word: 'ЧУХИН', translation: 'Inside / Inward' },
  { word: 'ЧУХОА', translation: 'To fit in / To contain' },
  { word: 'ЧУХОО', translation: 'To place inside' },
  { word: 'ЧУХТА', translation: 'Cap / Bonnet (traditional)' },
  { word: 'ЧУЧАЛ', translation: 'Scarecrow / Effigy' },
  { word: 'ЧУЧЧА', translation: 'Close to each other' },
  { word: 'ЧУЬРА', translation: 'Internal' },
  { word: 'ЧУЬРК', translation: 'Mosquito' },
  { word: 'ЧУЭЦА', translation: 'To take in' },
  { word: 'ЧХЬОЧ', translation: 'Sponge' },
  { word: 'ЧЁТНИ', translation: 'Even (number)' },
  { word: 'ЧӀАБА', translation: 'Braid / Pigtail' },
  { word: 'ЧӀАМА', translation: 'Forelock' },
  { word: 'ЧӀАНА', translation: 'Bare / Naked' },
  { word: 'ЧӀАНО', translation: 'Bareness / Baldness' },
  { word: 'ЧӀАПА', translation: 'Flat' },
  { word: 'ЧӀАРА', translation: 'Fish' },
  { word: 'ЧӀЕГА', translation: 'Ring / Link' },
  { word: 'ЧӀЕРГ', translation: 'Wick' },
  { word: 'ЧӀИКЪ', translation: 'Chirp / Squeak' },
  { word: 'ЧӀИНГ', translation: 'Chin' },
  { word: 'ЧӀИНТ', translation: 'Button' },
  { word: 'ЧӀоДА', translation: 'Whip / Lash' },
  { word: 'ШАБАР', translation: 'Whisper' },
  { word: 'ШАЛГО', translation: 'Twin / Double' },
  { word: 'ШАЛХА', translation: 'Double / Dual' },
  { word: 'ШАЛXO', translation: 'Duality / Hypocrisy' },
  { word: 'ШАРАМ', translation: 'Scar' },
  { word: 'ШАРАН', translation: 'Ice (genitive)' },
  { word: 'ШАРША', translation: 'To slide / To slip' },
  { word: 'ШАРШО', translation: 'To slide something' },
  { word: 'ШАРШУ', translation: 'Bedspread / Sheet' },
  { word: 'ШАТУН', translation: 'Connecting rod' },
  { word: 'ШАХТА', translation: 'Mine / Shaft' },
  { word: 'ШЕВРО', translation: 'Kidskin leather' },
  { word: 'ШЕДАГ', translation: 'Candle' },
  { word: 'ШЕДАН', translation: 'To knot / To tie' },
  { word: 'ШЕКАР', translation: 'Sugar' },
  { word: 'ШЕҚЪА', translation: 'Ink' },
  { word: 'ШЕЛАШ', translation: 'Specific / Localized' },
  { word: 'ШЕЛИГ', translation: 'Bucket / Pail' },
  { word: 'ШЕЛӀА', translation: 'Specific / Localized' },
  { word: 'ШЕНАШ', translation: 'Themselves' },
  { word: 'ШЕНИГ', translation: 'His/Her own' },
  { word: 'ШЕННА', translation: 'Separately / Alone' },
  { word: 'ШЕРАН', translation: 'Annual / Year’s' },
  { word: 'ШЕРАШ', translation: 'Years' },
  { word: 'ШЕРЕТ', translation: 'Sharia law' },
  { word: 'ШЕРШО', translation: 'Leveling / Smoothing' },
  { word: 'ШЕТАН', translation: 'Satan' },
  { word: 'ШИБӀЕ', translation: 'Two hundred' },
  { word: 'ШИВАН', translation: 'Siva (Proper name)' },
  { word: 'ШИЙЛА', translation: 'Cold' },
  { word: 'ШИЙЛО', translation: 'To cool / Coldness' },
  { word: 'ШИММО', translation: 'Both' },
  { word: 'ШИНАН', translation: 'Tuesday / Two’s' },
  { word: 'ШИФЕР', translation: 'Slate' },
  { word: 'ШИФОН', translation: 'Chiffon' },
  { word: 'ШИЧИН', translation: 'Cousin’s' },
  { word: 'ШИШАЙ', translation: 'Bottle' },
  { word: 'ШИШША', translation: 'Two each' },
  { word: 'ШКАЛА', translation: 'Scale' },
  { word: 'ШКОЛА', translation: 'School' },
  { word: 'ШОВДА', translation: 'Spring / Fountain' },
  { word: 'ШОВҚЪ', translation: 'Passion / Inspiration' },
  { word: 'ШОЗЗА', translation: 'Twice' },
  { word: 'ШОЛАН', translation: 'Second / Other' },
  { word: 'ШОНАШ', translation: 'Years (plural variant)' },
  { word: 'ШОРТА', translation: 'Plenty / Abundant' },
  { word: 'ШОРТО', translation: 'Abundance / Space' },
  { word: 'ШОФЁР', translation: 'Driver / Chauffeur' },
  { word: 'ШОЧАН', translation: 'Sarsaparilla' },
  { word: 'ШПАЛА', translation: 'Sleeper / Tie' },
  { word: 'ШПИОН', translation: 'Spy' },
  { word: 'ШПРИЦ', translation: 'Syringe' },
  { word: 'ШРИФТ', translation: 'Font / Script' },
  { word: 'ШТАМП', translation: 'Stamp' },
  { word: 'ШТРЕК', translation: 'Drift / Gallery' },
  { word: 'ШУНАН', translation: 'Your (plural) / Table’s' },
  { word: 'ШУРИН', translation: 'Milk’s' },
  { word: 'ШУРУЛ', translation: 'Abundance' },
  { word: 'ШУРУП', translation: 'Screw' },
  { word: 'ЩЁТКА', translation: 'Brush' },
  { word: 'ЭВНАШ', translation: 'Wounds' },
  { word: 'ЭДАЛА', translation: 'Specific / Localized' },
  { word: 'ЭККХА', translation: 'To burst / To explode' },
  { word: 'ЭККХО', translation: 'To drive out / To expel' },
  { word: 'ЭКРАН', translation: 'Screen' },
  { word: 'ЭЛИЙН', translation: 'Noble / Princes’' },
  { word: 'ЭЛТАР', translation: 'Letter / Symbol' },
  { word: 'ЭМАЛК', translation: 'Untamed horse' },
  { word: 'ЭМГАР', translation: 'Rival wife' },
  { word: 'ЭМКАЛ', translation: 'Camel' },
  { word: 'ЭМОЦИ', translation: 'Emotion' },
  { word: 'ЭНИЙН', translation: 'Pound’s' },
  { word: 'ЭПОХА', translation: 'Epoch / Era' },
  { word: 'ЭППАЗ', translation: 'Abbas (coin)' },
  { word: 'ЭПСАР', translation: 'Officer' },
  { word: 'ЭРЗАН', translation: 'Reed’s' },
  { word: 'ЭРИНА', translation: 'In vain / Useless' },
  { word: 'ЭСАЛА', translation: 'Gentle / Submissive' },
  { word: 'ЭСАРШ', translation: 'Felt boots' },
  { word: 'ЭСКАР', translation: 'Army / Troops' },
  { word: 'ЭСКИЗ', translation: 'Sketch' },
  { word: 'ЭТТӀА', translation: 'Torn / Split' },
  { word: 'ЭФИОП', translation: 'Ethiopian' },
  { word: 'ЭХАНГ', translation: 'Half-half' },
  { word: 'ЭХАРТ', translation: 'Afterlife' },
  { word: 'ЭШАРШ', translation: 'Songs / Melodies' },
  { word: 'ЮБКИН', translation: 'Skirt’s' },
  { word: 'ЮКҚЪЕ', translation: 'Middle / Center' },
  { word: 'ЮҚЪЯН', translation: 'To divide' },
  { word: 'ЮННАТ', translation: 'Young naturalist' },
  { word: 'ЮННИГ', translation: 'The one that is' },
  { word: 'ЮРИСТ', translation: 'Lawyer' },
  { word: 'ЮТҚЪА', translation: 'Thin / Slender' },
  { word: 'ЮТҚЪО', translation: 'To thin out' },
  { word: 'ЮЬҚЪА', translation: 'Thick / Dense' },
  { word: 'ЮЬҚЪО', translation: 'To thicken' },
  { word: 'ЮЬМАН', translation: 'Specific / Localized' },
  { word: 'ЮЬСТЕ', translation: 'Aside / To the side' },
  { word: 'ЮЬХАН', translation: 'Beginning / Face' },
  { word: 'ЯАЯЛА', translation: 'To be eaten' },
  { word: 'ЯГОРГ', translation: 'Fuel / Combustible' },
  { word: 'ЯЗДАН', translation: 'To write' },
  { word: 'ЯЗДАР', translation: 'Writing' },
  { word: 'ЯЗЪЯН', translation: 'To write down' },
  { word: 'ЯЙЛЛА', translation: 'Died (female)' },
  { word: 'ЯЙНИГ', translation: 'Lightweight (female)' },
  { word: 'ЯЙЯЛА', translation: 'To get lost' },
  { word: 'ЯККХА', translation: 'To take / To spend time' },
  { word: 'ЯЛгӀУ', translation: 'Copper pot' },
  { word: 'ЯЛКХА', translation: 'Nape / Back of head' },
  { word: 'ЯЛПАР', translation: 'Grease' },
  { word: 'ЯЛТИН', translation: 'Grain’s / Harvest’s' },
  { word: 'ЯМБАШ', translation: 'Iambic' },
  { word: 'ЯНТОР', translation: 'Amber' },
  { word: 'ЯРСТА', translation: 'To get fat' },
  { word: 'ЯРСТО', translation: 'To fatten' },
  { word: 'ЯРТАШ', translation: 'Villages' },
  { word: 'ЯСАКХ', translation: 'Tribute / Tax' },
  { word: 'ЯХХАШ', translation: 'Faces / Cheeks' },
  { word: 'ЯХЪЯН', translation: 'To lengthen' },
  { word: 'ЯЦЪЯН', translation: 'To shorten' },
  { word: 'ЯЬӀНА', translation: 'Shoulder blade' },
  { word: 'ЯЬССА', translation: 'Empty' },
  { word: 'ЯЬШКА', translation: 'Box / Case' },
  { word: 'ӀАЙТА', translation: 'To cough' },
  { word: 'ӀАРБИ', translation: 'Arab' },
  { word: 'ӀАХКА', translation: 'To lie / To be situated' },
  { word: 'ӀАХКО', translation: 'To lay down' },
  { word: 'ӀАЬӀА', translation: 'To gather / To accumulate' },
  { word: 'ӀЕЛИН', translation: 'Ali’s' },
  { word: 'ӀЕТТO', translation: 'To vomit / To spill' },
  { word: 'ӀИЙДА', translation: 'To pull / To draw' },
  { word: 'ӀИЙЖА', translation: 'To ache / To sting' },
  { word: 'ӀИЙЖО', translation: 'To cause pain' },
  { word: 'ӀИЙША', translation: 'To need / To lack' },
  { word: 'ӀИЛЛА', translation: 'Lied down' },
  { word: 'ӀИЛЛО', translation: 'To lay' },
  { word: 'ӀИЛМА', translation: 'science / Knowledge' },
  { word: 'ӀИТТА', translation: 'To push / To stab' },
  { word: 'ӀОВДА', translation: 'To squeeze / To milk' },
  { word: 'ӀОВЖА', translation: 'To ache' },
  { word: 'ӀОВЖО', translation: 'To cause ache' },
  { word: 'ӀОВША', translation: 'To taste / To chew' },
  { word: 'ӀОТТА', translation: 'To stick / To push' },
  { word: 'ӀУЬРГ', translation: 'Hole' },
  { word: 'ӀУЬӀА', translation: 'To prod / To poke' }
];

export const ALPHABET = [
  ['Й', 'Ц', 'У', 'К', 'Е', 'Н', 'Г', 'Ш', 'Щ', 'З', 'Х', 'Ъ'],
  ['Ф', 'Ы', 'В', 'А', 'П', 'Р', 'О', 'Л', 'Д', 'Ж', 'Э'],
  ['Я', 'Ч', 'С', 'М', 'И', 'Т', 'Ь', 'Б', 'Ю', 'Ӏ']
];